### ISSUE TITLE
Pedal request: JOYO PXL8

### ISSUE THREAD

**Issue by ghost** [PedalPlayground/PedalPlayground.github.io#1003]
W: 17.83in
H: 2.64in

![joyo_pxl8](https://user-images.githubusercontent.com/57646065/170373091-c79e228d-c765-48a8-ad80-1417c6bbaa0f.png)

**Comment by dvr994** [comment]
@ArislanShiva can you open a pull request for this issue and the other following issues?
#976 
#995 
#996 
#997 
#998 
#999 
#1000 
#1002

**Comment by ArislanShiva** [comment]
Please don't @ me with requests.

**Comment by dvr994** [comment]
> Please don't @ me with requests.

:/ sorry

**Comment by ArislanShiva** [comment]
Just a heads up, I may get around to doing the Joyo pedals one day, but the others I have no plans to tackle.  If XlosVSM doesn't plan on doing them either, then you may have to add them yourself.

**Comment by dvr994** [comment]
Ok it's good to me, but i never did it so someone should explain to me how to do it. Maybe can you or XlosVSM teach me?

**Comment by ArislanShiva** [comment]
https://github.com/PedalPlayground/PedalPlayground.github.io#contributing

**Comment by dvr994** [comment]
> https://github.com/PedalPlayground/PedalPlayground.github.io#contributing

Ok, but first i need to open a pull request? Or can i directly update photos and dimensions on the related folders?

**Comment by ArislanShiva** [comment]
https://www.dataschool.io/how-to-contribute-on-github/
