### ISSUE TITLE
Edit request: MISC PEDALS' DIMENSIONS

### ISSUE THREAD

**Issue by ghost** [PedalPlayground/PedalPlayground.github.io#1019]
The following pedal's dimensions are wrong:

Rowin/donner pedals: The dimensions are to be considered without jacks' encumbrance, so they need to be enlarged. Check the height as well.

Vick audio pedals: The dimensions are to be considered without jacks' encumbrance, so they need to be enlarged. The V2 dimensions are wrong, it's not equal to the other pedals, it's bigger: W: 3.70 in - H: 4.72 in. (always without jacks' encumbrance).

JIMI HENDRIX UNIVIBE: Dimensions are wrong, it's a classic MXR standard.

**Comment by tehtrav** [comment]
I believe the contributor who took the time to upload the 12 or so pedals you requested used the dimensions that [you supplied](https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1004) with the requests.

**Comment by dvr994** [comment]
> I believe the contributor who took the time to upload the 12 or so pedals you requested used the dimensions that [you supplied](https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1004) with the requests.

Yes, the main difference is about the jacks' encumbrance. See the following drawing:
![errore V2](https://user-images.githubusercontent.com/57646065/173189091-8748159c-0fc9-4d5a-859e-9271c4096d08.JPG)

The green pedal below shows the real dimensions of the pedal. The only difference is about the jacks' position. Jacks' encumbrance has to be considered off the pedal enclosure area. It needs to be reworked another time.

The same issue is equal for Vick audio '73 Ram's Head and 1861, but their dimensions are W: 2.25in - H: 4.25. For every pedal i have indicated the related dimensions. See the following drawing:

![errore 2](https://user-images.githubusercontent.com/57646065/173189555-348683b7-738f-4e75-a774-d49d6f4cb2ac.JPG)
