### ISSUE TITLE
Action buttons rotate with custom pedals

### ISSUE THREAD

**Issue by tandrewnichols** [PedalPlayground/PedalPlayground.github.io#103]
When you rotate a custom pedal, the action buttons (rotate/delete) rotate too, which makes it difficult to rotate multiple times quickly. Regular pedals don't have this problem because the `transform: rotate` is applied to the `artwork` background-image div rather than the containing div. I looked briefly at fixing this, but it turned out to be more complicated than I thought it would be.

**Comment by tehtrav** [comment]
Fixed
