### ISSUE TITLE
Pedal Request: D'Addario CT-20 Tuner

### ISSUE THREAD

**Issue by Isaac-Y-5** [PedalPlayground/PedalPlayground.github.io#1042]
![daddario-ct20-tuner](https://user-images.githubusercontent.com/78507664/174886038-caba6f93-7856-49d3-ab75-fb868797dc14.png)

Dimensions: 2" x 4.8" (WxH)

Thank You!

**Comment by ArislanShiva** [comment]
It's already in the database, named: "D'Addario Tuner"

I updated the name to CT-20 and added the CT-23 as well.
