### ISSUE TITLE
Pedal Request: Rock Stock Pedals Nano Tuner

### ISSUE THREAD

**Issue by btbrown22** [PedalPlayground/PedalPlayground.github.io#1064]
Dimensions: 1.8" x 1.7"

<img width="492" alt="Nano Tuner" src="https://user-images.githubusercontent.com/105957136/179268097-360b8188-f071-490d-877a-e3916f4ca6f2.png">

**Comment by ArislanShiva** [comment]
It's just a rebranded Swiff Audio tuner, which is already in the database
