### ISSUE TITLE
Pedal Request - Funny Little Boxes 1991

### ISSUE THREAD

**Issue by AdamDav1979** [PedalPlayground/PedalPlayground.github.io#1086]
Hi, As above. Please could you add the FLB 1991 pedal please. Photo and dimensions attached. Regards, Adam
![1991 Pedal](https://user-images.githubusercontent.com/109955010/180748825-1acbd316-7def-4443-b5be-57fa423728c4.jpg)

Dimensions: H 4.715 Inches x W 2.553 Inches.

**Comment by ArislanShiva** [comment]
It's already in the database
