### ISSUE TITLE
Fix dimensions- MI Audio Crunchbox V2

### ISSUE THREAD

**Issue by acousticsamurai** [PedalPlayground/PedalPlayground.github.io#1089]
Requesting to fix MI Audio Crunchbox v2's width to 2.2" not including the tip of the input and output jack. Thank you!

**Comment by drg994** [comment]
The dimension you read is enlarged in order to exclude the jacks. You can use a 12" ruler to take the measure and verify it ;)

![image](https://user-images.githubusercontent.com/107513306/181094495-d908ff80-e0b3-4438-a11d-11260de06d35.png)

**Comment by acousticsamurai** [comment]
You're right. I don't have a ruler but I have the actual pedals in front of me for comparison. The Plexi-Drive definitely needs to be bigger.
![18286494-88AC-4F0B-83D5-FDFBF3ED90F7](https://user-images.githubusercontent.com/105616913/181098190-6dd5796a-0db2-4fae-97e1-64900827bbfb.jpeg)
![C16F6D99-19B4-4EBA-86E9-96511C7529F8](https://user-images.githubusercontent.com/105616913/181098195-52255e06-7957-44db-933e-1bc5031afba4.jpeg)

**Comment by drg994** [comment]
> You're right. I don't have a ruler but I have the actual pedals in front of me for comparison. The Plexi-Drive definitely needs to be bigger. ![18286494-88AC-4F0B-83D5-FDFBF3ED90F7](https://user-images.githubusercontent.com/105616913/181098190-6dd5796a-0db2-4fae-97e1-64900827bbfb.jpeg) ![C16F6D99-19B4-4EBA-86E9-96511C7529F8](https://user-images.githubusercontent.com/105616913/181098195-52255e06-7957-44db-933e-1bc5031afba4.jpeg)

Agree with you about the plexi-drive.

**Comment by drg994** [comment]
@acousticsamurai Yes, agree with you about the plexi-drive.

**Comment by ArislanShiva** [comment]
The total width of the MI Crunchbox v2 with jacks should be ~2.6 inches given a height of 4.3

> (image width / image height) x 4.3

**Comment by ArislanShiva** [comment]
I just went ahead and added the entire MI Audio lineup, including a new version of this pedal

**Comment by drg994** [comment]
@ArislanShiva so which would be the correct dimensions? Mine was 2.2" without jacks and 2.6" including jacks. Given a height of 4.3".

**Comment by ArislanShiva** [comment]
@drg994 the width in the db was set to 2.52.  Notice how the knobs in your image above are more ovals than perfect circles.  That's how you can tell your aspect ratio vs measurements are a bit off for the image.

**Comment by drg994** [comment]
> @drg994 the width in the db was set to 2.52. Notice how the knobs in your image above are more ovals than perfect circles. That's how you can tell your aspect ratio vs measurements are a bit off for the image.

Yes, you're right. I just noticed that the original image is slightly oval.
