### ISSUE TITLE
Fix dimensions- Wampler Plexi-Drive (Original Design)

### ISSUE THREAD

**Issue by acousticsamurai** [PedalPlayground/PedalPlayground.github.io#1090]
Requesting to fix Wampler Plexi-Drive (Original Design) dimensions to:

W - 2.5”
H - 4.5”

Pedal width and height shouldn't include tip of jacks. Thanks!

**Comment by ArislanShiva** [comment]
With the given image, the total size of the pedal should be including all protrusions:

Width: 2.84
Height: 4.87


I went ahead and fixed it.

**Comment by acousticsamurai** [comment]
Thank you so much! I appreciate everything that you guys do. This site is so addicting.
