### ISSUE TITLE
Pedal Request: Aclam The Woman Tone

### ISSUE THREAD

**Issue by valdeur** [PedalPlayground/PedalPlayground.github.io#1100]
"Brand": "Aclam",
"Name": "The Woman Tone",
"Width": 5.4,
"Height": 3.4,
"Image": "aclam-thewomantone.png"
![aclam-thewomantone](https://user-images.githubusercontent.com/34281805/183078381-2eb0448a-b178-4c89-a057-22407aae360d.png)

**Comment by ArislanShiva** [comment]
Already in the db
