### ISSUE TITLE
Pedal request: Dunlop QZ1 Crybaby Q-Zone (original)

### ISSUE THREAD

**Issue by acousticsamurai** [PedalPlayground/PedalPlayground.github.io#1140]
![6F5A9C22-298C-41E8-A5F5-4FFAC88149C3](https://user-images.githubusercontent.com/105616913/187318250-621c4016-d2f9-4c6b-9099-3878b0ec801d.jpeg)

**Comment by ArislanShiva** [comment]
Hey, I know you requested the original, but it's almost identical to the current version so I added the current one instead.  Better image sources and I suspect the community would get more use out it.

**Comment by acousticsamurai** [comment]
I actually have both but just prefer the look and build quality of the original. The new one will do, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
