### ISSUE TITLE
Add BOSS GE-7 Graphic Equalizer

### ISSUE THREAD

**Issue by MaoZhengfu** [PedalPlayground/PedalPlayground.github.io#116]
Dimensions are 2.4" x 2.9".

![ge7](https://user-images.githubusercontent.com/48335276/54029252-c72b6600-4175-11e9-9e3c-0f65993c9142.jpg)

Thank you!

**Comment by MaoZhengfu** [comment]
Dimensions are 2.4" x 2.9".
![ge7](https://user-images.githubusercontent.com/48335276/54029205-a06d2f80-4175-11e9-9821-79ec72028987.jpg)

**Comment by tehtrav** [comment]
added
