### ISSUE TITLE
Request pedal fix: Dunlop Cry Baby Q Zone

### ISSUE THREAD

**Issue by acousticsamurai** [PedalPlayground/PedalPlayground.github.io#1162]
![4C942BE0-8F7E-4871-AE23-2E49201B90BF](https://user-images.githubusercontent.com/105616913/188880285-0d039313-7f18-49c4-a6e0-2953a8c33bfa.png)

Pedal not showing up.

**Comment by ArislanShiva** [comment]
Sorry about that, it was a bit of carelessness on my part.

**Comment by acousticsamurai** [comment]
No worries. Thank you for all you do.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acousticsamurai** [comment]
Hello,
Just letting you know that the request was closed but the issue wasn't been resolved.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
