### ISSUE TITLE
Pedal request fix: Dunlop Cry Baby Q Zone

### ISSUE THREAD

**Issue by acousticsamurai** [PedalPlayground/PedalPlayground.github.io#1179]
Submitted a request last week. The ticket was closed but the issue wasn't resolved. Thanks. 
![3E8FF930-6899-4CB7-A477-2E4FC5358BE2](https://user-images.githubusercontent.com/105616913/190877769-53dd22ce-9fc0-48c4-b041-2fd4cbceb202.png)

**Comment by XlosVSM** [comment]
A check failed when our PRs were being built, so the changes were never submitted to the website.
