### ISSUE TITLE
GCB Wahs

### ISSUE THREAD

**Issue by 32Pedalboards** [PedalPlayground/PedalPlayground.github.io#1189]
What the heck happened to all the Dunlop GCB Wahs ??

**Comment by 32Pedalboards** [comment]
In fact there are a LOT of broken pedals. mini 535q is invisible, as an example. Looks like a bunch of image assets have been nuked as well as pedals themselves.

**Comment by ArislanShiva** [comment]
@XlosVSM has been busy renaming image files in the database, I'm guessing he accidentally broke a few.

**Comment by Ripley63** [comment]
Yes, the Dunlop Mini 535Q Wah only has a placeholder-box, too. The image is gone.
