### ISSUE TITLE
New Pedals

### ISSUE THREAD

**Issue by WhiteDeath15** [PedalPlayground/PedalPlayground.github.io#119]
Add Joyo US Dream

**Comment by WhiteDeath15** [comment]
Add Joyo Sweet Baby

**Comment by tehtrav** [comment]
Please follow the following rules when posting request issues:

- Include a decent resolution image of the pedal (top-down view, white background)
- Include the dimensions, in inches (make sure the dimensions are accurate and include jacks and other protrusions)
- Post one issue for each pedal you're requesting
