### ISSUE TITLE
Pedal Request: Free The Tone CW-1Y Cosmic Wave Multiple Filtering Delay

### ISSUE THREAD

**Issue by SouthPawRP** [PedalPlayground/PedalPlayground.github.io#1229]
![image](https://user-images.githubusercontent.com/116117343/196536955-c77210e5-3553-462f-aa61-064c070c62c6.png)

2.6 X 4.64

**Comment by ArislanShiva** [comment]
This pedal is already in the database

**Comment by SouthPawRP** [comment]
Am I missing something? 

![image](https://user-images.githubusercontent.com/116117343/196704371-129d6fec-3979-4b5f-b6c3-eddfaa558ea3.png)
![image](https://user-images.githubusercontent.com/116117343/196704521-86083fc8-8bd7-4ee4-b5f1-b5a393aedeba.png)
![image](https://user-images.githubusercontent.com/116117343/196704636-861b42b0-4286-4829-bb4a-de5d001f242b.png)

**Comment by SouthPawRP** [comment]
I saw your thread where it was added in Sept. but I cannot seem to locate
it.

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by ArislanShiva** [comment]
Sorry my bad, the pedal was done awhile ago, but hasn't been pulled into the main branch yet.

**Comment by SouthPawRP** [comment]
Ah, got it! Thanks!

**Comment by SouthPawRP** [comment]
FYI - I'm still not seeing it on the site.
