### ISSUE TITLE
Pedal Request: Walrus Audio Eons 5-state Fuzz Pedal

### ISSUE THREAD

**Issue by Izovaprophet** [PedalPlayground/PedalPlayground.github.io#1256]
Width: 2.62
Height: 4.77

![walrus-audio-eons-fuzz](https://user-images.githubusercontent.com/116752787/198098349-b0e0e19b-ef3e-4618-bb74-f4d6cdc16d68.png)

**Comment by ArislanShiva** [comment]
This one's already been added to the database.  Please give the site some time to update to the latest build.
