### ISSUE TITLE
Pedal Request: LR Baggs Align Series

### ISSUE THREAD

**Issue by cp420what** [PedalPlayground/PedalPlayground.github.io#1258]
![align-series-reverb-acoustic-pedal-1_preview_rev_1](https://user-images.githubusercontent.com/90297037/198857381-8b377a01-8bd2-4fae-96f4-aa80b0f46bcb.png)
LR Baggs Align Series Reverb
3.25” x 5”

![align-series-session-acoustic-pedal-1_preview_rev_1](https://user-images.githubusercontent.com/90297037/198857464-1474e748-8003-4359-80da-98c5874a10bc.png)
LR Baggs Align Series Session
3.25" x 5"

![align-series-chorus-acoustic-pedal-1_preview_rev_1](https://user-images.githubusercontent.com/90297037/198857470-30e893e4-f2e7-4f8b-ac34-5d8bdbc3f3ba.png)
LR Baggs Align Series Chorus
3.25" x 5"

![align-series-delay-acoustic-pedal-1_preview_rev_1](https://user-images.githubusercontent.com/90297037/198857475-5844fc05-5921-4615-b474-c15521f4ad5a.png)
LR Baggs Align Series Delay
3.25" x 5"

![align-series-equalizer-acoustic-pedal-1_preview_rev_1](https://user-images.githubusercontent.com/90297037/198857481-c65b434f-0cb0-4883-978a-ca1e0fb87104.png)
LR Baggs Align Series Equalizer
3.25" x 5"

![align-series-active-di-acoustic-pedal-1_preview_rev_2](https://user-images.githubusercontent.com/90297037/198857484-7270df7e-e994-4e92-9322-d891a394365c.png)
LR Baggs Align Series Active DI
3.25" x 5"

**Comment by ArislanShiva** [comment]
These have been requested already and have been added to the db.  Please be patient as the site updates to the latest build.

**Comment by cp420what** [comment]
My apologies. I should have checked first. Thanks.On Oct 30, 2022, at 7:09 AM, ArislanShiva ***@***.***> wrote:﻿
These have been requested already and have been added to the db.  Please be patient as the site updates to the latest build.
