### ISSUE TITLE
Pedal Request - JHS Artificial Blonde

### ISSUE THREAD

**Issue by brahen90** [PedalPlayground/PedalPlayground.github.io#1261]
I have the photos to add to this but I lack the knowledge to do so.
THIS PEDALS MEASURES 4.7” X 3.5” X 1.5”
![dk4qkzijgcddlssjxmdj-324705981 Background Removed](https://user-images.githubusercontent.com/117392381/199812446-354448ec-c76d-4954-9705-852c6939e79d.png)

**Comment by ArislanShiva** [comment]
This one was added previously, but we're still waiting for the site to update to the current build.
