### ISSUE TITLE
Pedal Request: Audio Sprockets ToneDexter II

### ISSUE THREAD

**Issue by tdillonsd** [PedalPlayground/PedalPlayground.github.io#1307]
![Audio Sprockets Tone Dexter II](https://user-images.githubusercontent.com/52335215/207701558-823b0694-123e-4d87-a8d4-31b247296b51.jpg)

6.3″ W x 5.9″ D

**Comment by ArislanShiva** [comment]
Do you have any pics of the jacks/knobs on this thing?  I know it's yet unreleased, but the version 1 looks like it had some long knobs sticking out the back which will be important to include here.

**Comment by tdillonsd** [comment]
![Audio Sprockets Tone Dexter I](https://user-images.githubusercontent.com/52335215/207905200-f435853b-9bff-42fe-818e-a5a8f29c14b7.jpg)

I can't locate another image of the unreleased version II, but here is a jpeg the old version I of this pedal showing the rear knobs and jacks. Version II has jacks in the same places but no knobs on the back.  If this jpeg is a more workable image, let's use it and go with Tone Dexter I for this request. It's the same footprint as the new version II except for the rear knobs and it will work for my needs. I can make a request for version II in the future when there are more released images.

Should I trim away the white background?

**Comment by ArislanShiva** [comment]
Nah, I'll take it from here, thanks!
