### ISSUE TITLE
Pedal Request: NUX NMP-2 Dual Footswitch Controller

### ISSUE THREAD

**Issue by reubenwalkerau** [PedalPlayground/PedalPlayground.github.io#1311]
Dimensions: 4.6cm x 9.5cm

![NUX-NX-NMP2](https://user-images.githubusercontent.com/25394294/208233330-9e3489e5-4404-4aa7-a4c0-e70f2e92a2bb.png)

Thank you

**Comment by ArislanShiva** [comment]
This one is already in the database.
