### ISSUE TITLE
Case sensitive files in repo

### ISSUE THREAD

**Issue by ericraymond** [PedalPlayground/PedalPlayground.github.io#133]
When cloning repo on a Mac we get the following issue.  Looks like these are just accidental duplications of the same file.

Warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'public/images/pedals/catalinbread-BicycleDelay.png'
  'public/images/pedals/catalinbread-bicycledelay.png'
  'public/images/pedals/catalinbread-Discman.png'
  'public/images/pedals/catalinbread-discman.png'
  'public/images/pedals/catalinbread-GeKarma.png'
  'public/images/pedals/catalinbread-gekarma.png'
  'public/images/pedals/catalinbread-SiKarma.png'
  'public/images/pedals/catalinbread-sikarma.png'

**Comment by tehtrav** [comment]
Fixed
