### ISSUE TITLE
Pedal request : Kasleder Toxic Twins

### ISSUE THREAD

**Issue by Loscorp** [PedalPlayground/PedalPlayground.github.io#1339]
An incredible dual overdrive !

Brand: Kasleder
Model: Toxic Twins
Dimensions: 120 x 97 mm / 4.72 x 3.82 in

![Kasleder Toxic Twins](https://user-images.githubusercontent.com/121567974/209839886-b253929f-d44b-4b89-a677-6d9e1f922c7a.png)

**Comment by Loscorp** [comment]
Hi !
Apparently one of the pedals I proposed (Kasleder Tooxic Twins) has been added, but it does not appear on the pedalplayground site when I want to add it to my pedalboard.
Is there a delay before it appears?
Thanks.
Best.
Laurent

De : Travis Lehman ***@***.***>
Répondre à : "PedalPlayground/PedalPlayground.github.io" ***@***.***>
Date : lundi 23 janvier 2023 à 21:10
À : "PedalPlayground/PedalPlayground.github.io" ***@***.***>
Cc : Loscorp ***@***.***>, Author ***@***.***>
Objet : Re: [PedalPlayground/PedalPlayground.github.io] Pedal request : Kasleder Toxic Twins (Issue #1339)


Closed #1339<https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1339> as completed via #1265<https://github.com/PedalPlayground/PedalPlayground.github.io/pull/1265>.

**Comment by ArislanShiva** [comment]
Please allow about an hour or so for the build and deployment to complete.
