### ISSUE TITLE
Pedal Request: Tinsley Audio Sir Henry Vibe 

### ISSUE THREAD

**Issue by patrick-amdahl** [PedalPlayground/PedalPlayground.github.io#1357]
Pedal Dimensions: 8.09" x 4.7"

8.09" includes the .71" for the knob.  Enclosure is 7.38"

![sirhenry](https://user-images.githubusercontent.com/71848157/211932693-8606b2b1-169f-49ac-a3cd-61cff230c3dc.png)
![sirhenry350](https://user-images.githubusercontent.com/71848157/211932714-72966120-d351-4250-b005-3051b54eaa5b.png)
![sirhenry800](https://user-images.githubusercontent.com/71848157/211932716-3c05311a-1a3f-412a-b6ca-4cd55c4a084f.png)

**Comment by patrick-amdahl** [comment]
@tehtrav @ArislanShiva - I may be missing something but I dont see the Sir Henry Vibe in #1265.

Thanks!

**Comment by ArislanShiva** [comment]
Please allow about an hour or so for the build and deployment to complete.

**Comment by patrick-amdahl** [comment]
ahh gotcha - thanks for clarifying
