### ISSUE TITLE
Dunlop Mini 535Q Wah disappeared?

### ISSUE THREAD

**Issue by Ripley63** [PedalPlayground/PedalPlayground.github.io#1360]
Its placeholder loads, with no image.
What gives?

**Comment by ArislanShiva** [comment]
https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1189

**Comment by XlosVSM** [comment]
Delete it and replace it

**Comment by Ripley63** [comment]
No, deleting it doesn't work.
Did it already multiple times in Firefox, Chrome, Opera and Edge...

**Comment by XlosVSM** [comment]
I have removed the extra in my pr, it is now under the brand Cry Baby
