### ISSUE TITLE
Pedalboard Request: Pivotal Pedalboards

### ISSUE THREAD

**Issue by PivotalPedalboards** [PedalPlayground/PedalPlayground.github.io#1379]
**X14 Upper (Full Deck)** 
13.75" x 11.25"

![X14 Upper ](https://user-images.githubusercontent.com/119954542/214758285-87b17501-efce-4372-8932-f7a505b219e3.png)

**X14 Lower**
14" x 11.625"

![X14 Lower](https://user-images.githubusercontent.com/119954542/214758518-7a837735-9156-4023-be76-6725720b75f9.png)

**Comment by ArislanShiva** [comment]
Are you a representative of the company?

**Comment by PivotalPedalboards** [comment]
> Are you a representative of the company?

Yes

**Comment by ArislanShiva** [comment]
> Yes

I'm happy to work on this, but could you supply a top down photo of a complete board in each size?  I need to know where to put the hinges, clasps, rough dimensions, etc.  A diagram would work as well.

**Comment by ArislanShiva** [comment]
Also a top-down photo of your patch bay.

**Comment by PivotalPedalboards** [comment]
I initially took some top-down photos, but with black-on-black some of the no-go zones on the bottom deck weren't immediately obvious from that view. For example, the front pivoting arms and the small support blocks just behind the space for the patch bay. So I thought a digital diagram might be more useful and also wouldn't suffer from the perspective distortions of a top-down photo. These were created from actual measurements, with accurate positions of the hinges, etc., when scaled up to the dimensions I listed. Will that work or would you still prefer photos? I'm happy to accommodate.

I'll get a top-down photo of the patch bay either way. Should I just post the files here? Thanks so much for taking this on!

(I just double checked my measurements and noticed that the Upper Deck file was created with a document width of 14" but the actual measurement is 13.75", so technically the image will be compressed very slightly in the x axis when scaled to 13.75". This wouldn't make a noticeable difference. I can adjust and re-upload if necessary.)

**Comment by ArislanShiva** [comment]
The diagrams you provided are great for the pedal surfaces, but they don't provide any info on the outer enclosure.  Users would want to be able to see the whole board mocked up within the case.  Build plans/diagrams with exact dimensions would be best if you have those.  If not, just a top down photo (don't stress about the perspective) will work as well. 

Posting images and links here is perfectly fine.

**Comment by PivotalPedalboards** [comment]
Sounds good, thanks! I'll get on it.

**Comment by PivotalPedalboards** [comment]
I can expand the existing Lower diagrams to include the outer walls (all to scale), would that work? 

And is the Upper diagram suitable as-is or would you want to see it superimposed over the lower deck? I'm thinking it would be best left independent since the side walls don't rise up around it.

**Comment by ArislanShiva** [comment]
Yup, just on the lower ones please.

**Comment by PivotalPedalboards** [comment]
Only one upper deck shape for the X14, two variations for the X20, and three for the X26. 

**X14 Lower**
15.5" x 13.375"
![X14 Lower Updated](https://user-images.githubusercontent.com/119954542/214949817-82ba196d-04b9-44ee-a367-21b28911ae8a.png)


**X14 Upper (Full Deck)**
13.75" x 11.25"
![X14 Upper Updated](https://user-images.githubusercontent.com/119954542/214949848-3c0a4986-0a64-48fd-8677-2f2b0553832d.png)

**X20 Lower**
22" x 13.375"
![X20 Lower Updated](https://user-images.githubusercontent.com/119954542/214950122-3794cd46-8f27-4460-9391-400a746b1808.png)

**X20 Upper (Full Deck)**
20.25" x 11.25"
![X20 Upper (Full Deck) Update](https://user-images.githubusercontent.com/119954542/214950246-0ea04598-574f-4b1a-a16d-25b257efcd87.png)

**X20 Upper (Single Cutaway)**
20.25" x 11.25"
![X20 Upper (Single Cutaway) Update](https://user-images.githubusercontent.com/119954542/214950403-e03b5b4c-3d5f-413f-a15d-1692ef07936f.png)

**X26 Lower**
28" x 15.375"
![X26 Lower Updated](https://user-images.githubusercontent.com/119954542/214950467-768b1942-5c84-4227-bc1a-0df0571a531e.png)

**X26 Upper (Full Deck)**
26.25" x 13.25"
![X26 Upper (Full Deck) Updated](https://user-images.githubusercontent.com/119954542/214950616-32ddcc8f-0f63-486f-84a1-26fdc85b9c9e.png)

**X26 Upper (Single Cutaway)**
26.25" x 13.25"
![X26 Upper (Single Cutaway) Updated](https://user-images.githubusercontent.com/119954542/214950739-bd5e1a9b-0af4-4a8d-a8e6-d03ead516691.png)

**X26 Upper (Double Cutaway)**
26.25" x 13.25"
![X26 Upper (Double Cutaway) Updated](https://user-images.githubusercontent.com/119954542/214950788-0fb312cb-ae4a-4c7c-8bf7-aafd297c4427.png)


**I/O 6 Patch Bay**
2.81" x 4.81" (including jacks)
![I:O 6 Patch Bay](https://user-images.githubusercontent.com/119954542/214957470-1041a8d0-24f7-459a-b1f7-059ca125e23a.png)

**Comment by ArislanShiva** [comment]
Exactly what I needed, thanks!

**Comment by ArislanShiva** [comment]
Just a quick look at what the X26 looks like so far:

![pp-bottom](https://user-images.githubusercontent.com/14098250/215190553-cbe91677-3ad9-4f27-a049-40b4e59f4c71.png)

![pp-both](https://user-images.githubusercontent.com/14098250/215190558-650deaa7-44b6-46a7-8132-f0e7d3b38125.png)

**Comment by PivotalPedalboards** [comment]
Wow. Fantastic work. I didn't realize you were going to recreate the diagrams but I'm glad you did as these are far nicer than the simple ones I put together!

If the Upper will appear above the Lower as one image when selected in Pedal Playground, then this measurement will help with the proper spacing (front edge of the Upper deck to the inside edge of the front wall is 6.5" on all X Series boards). 

![Playground X26 preview measurement](https://user-images.githubusercontent.com/119954542/215195663-11286539-d9ab-4d40-9888-5ef417a85619.png)


Thanks again, excited to see the rest!

**Comment by ArislanShiva** [comment]
The way I've been handling multi-tiered boards is to have the top level on a separate layer so users can sandwich pedals in between.   Each layer will be uploaded as an independent pedalboard so it'll be up to the users to position and stack them.  

If you're curious to see how it works in practice, check out the Vertex boards and riser combos in the database.

**Comment by ArislanShiva** [comment]
A quick preview of what the assembled X26 looks like in the app:

![pivotal-test](https://user-images.githubusercontent.com/14098250/216401353-7a22c2bd-1432-4a86-8176-c7f9a2bc3de9.jpg)

**Comment by PivotalPedalboards** [comment]
This is great, thanks so much.
Have you been able to look at the others? Just curious - no rush. I'm grateful for all the work you're putting in here, but also very excited to see the other sizes.

**Comment by ArislanShiva** [comment]
Once I've built the initial AI template knocking out the rest moves pretty quickly.

**Comment by ArislanShiva** [comment]
All done w/ the X-Series, pushing everything now:

![pivotal-xseries](https://user-images.githubusercontent.com/14098250/218178586-8393000c-654d-408b-a1b9-c2ae86ffa01b.jpg)

**Comment by PivotalPedalboards** [comment]
Looks great, thanks again
