### ISSUE TITLE
Victory V4 Copper Guitar Amp

### ISSUE THREAD

**Issue by Jmregan2** [PedalPlayground/PedalPlayground.github.io#1403]
Different than the V4 preamp already uploaded

10.15" wide
6.85" deep
![Screenshot_20230212-084354](https://user-images.githubusercontent.com/111456398/218314757-aff9ea55-c8d7-472f-86bb-f84e1b2fdf55.png)

**Comment by ArislanShiva** [comment]
This was already added back in #1265 but isn't active in the main site yet.
