### ISSUE TITLE
Main Project Problem?

### ISSUE THREAD

**Issue by fcbittenca** [PedalPlayground/PedalPlayground.github.io#1406]
I have requested a pedal last year, @ArislanShiva was kind enough to help me with it.
Then I was informed I had to wait for @tehtrav to pull the files into the main project. No problem.

I think @tehtrav did pull the files, but I can´t see them online. It´s been months, so I wonder if something went wrong with that load.

Can anybody help? Appreciate that. Cheers from Brazil.

**Comment by ArislanShiva** [comment]
Travis pushed the update a couple of weeks ago but the build failed.

You can actually download [my branch](https://github.com/ArislanShiva/PedalPlayground.github.io) and [run an instance of the site on your local machine](https://github.com/ArislanShiva/PedalPlayground.github.io#running-locally) if you need your requests right now.

**Comment by fcbittenca** [comment]
I imagined something happened. Thank you @ArislanShiva.
I don´t need it right now, I wish I could help fix it.
