### ISSUE TITLE
Crazy Tube Circuits - Unobtanium

### ISSUE THREAD

**Issue by fabgraham** [PedalPlayground/PedalPlayground.github.io#1414]
![unobtainable_pedal](https://user-images.githubusercontent.com/10279790/219868248-67262778-f649-4461-af7f-4927fdbbdfe3.jpeg)

Dimensions:
Lenght: 5.7 inches
Height: 4 inches

Thank you!

**Comment by ArislanShiva** [comment]
This was already added in #1265 but isn't active on the main site yet.

**Comment by fabgraham** [comment]
Thanks - how does it work now? Is the list being slowly added to the main site?

**Comment by ArislanShiva** [comment]
We now wait for @tehtrav to pull the changes into the main project.
