### ISSUE TITLE
Alexander Wavelength

### ISSUE THREAD

**Issue by sldarwinx** [PedalPlayground/PedalPlayground.github.io#144]
Please add this pedal.
W: 2.6"
H: 4.7"
https://images.squarespace-cdn.com/content/v1/54a5d748e4b034981b4a71c8/1529429098192-1VH7P283G17IQAVYAOVM/ke17ZwdGBToddI8pDm48kDaEh9TLqFRX6mTgq72agC8UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8GRo6ASst2s6pLvNAu_PZdIRzMoSIdpCs7ji98nSQq8gTIPM5dC29IvfJWkjn3s3MJp4GcUgf9v8MJZXHXyWJiw/Wavelength-Front.jpg?format=750w

**Comment by tehtrav** [comment]
Just added this one!
