### ISSUE TITLE
Pedal Request : CBA Warped Vinyl HiFi Limited Copper

### ISSUE THREAD

**Issue by vinisamples** [PedalPlayground/PedalPlayground.github.io#1451]
![image](https://user-images.githubusercontent.com/110693519/224375955-5ff9a61f-b268-4ca4-92b7-6aa09e6b09f1.png)

**Comment by ArislanShiva** [comment]
We're not making alternate colorways.

**Comment by vinisamples** [comment]
> We're not taking requests for alternate colorways.

Appreciate your work, but you litterally did : https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1207

**Comment by ArislanShiva** [comment]
Travis asked us not to in the future.
