### ISSUE TITLE
Rockbox Boiling Point Hand Painted

### ISSUE THREAD

**Issue by adewinne** [PedalPlayground/PedalPlayground.github.io#1456]
![Rockbox Boiling Point Hand Painted](https://user-images.githubusercontent.com/1494837/224511712-3f7bd8ac-b9aa-4dac-9cae-bed3e35d1b56.png)

4.72 x 2.56

**Comment by ArislanShiva** [comment]
Sorry we're no longer accepting alternate colorways/version of pedals.
