### ISSUE TITLE
Mesa Boogie - Flux Five

### ISSUE THREAD

**Issue by tamirsh777** [PedalPlayground/PedalPlayground.github.io#1461]
![flux five](https://user-images.githubusercontent.com/127890118/225111077-fa0853e4-e708-4749-9cf5-c0711419ed39.png)
Dimensions (W/D/H): 5.78" x 4.76" x 2.30" (146.8mm x 121mm x 58.4mm)

**Comment by ArislanShiva** [comment]
This one is covered in #1439

**Comment by tamirsh777** [comment]
I can't find it.

**Comment by tamirsh777** [comment]
You've added the "Mesa Boogie Flux Drive", not the "Flux Five". It looks
like this:
[image: Mesa Boogie Flux Five.png]

‪On Mon, May 1, 2023 at 4:39 PM ‫תמיר שרעבי‬‎ ***@***.***> wrote:‬

**Comment by ArislanShiva** [comment]
The PR that closes your issue hasn't been been pulled into the project yet: #1439
