### ISSUE TITLE
Pedal Request : Chase Bliss Audio Mood MKII

### ISSUE THREAD

**Issue by vinisamples** [PedalPlayground/PedalPlayground.github.io#1463]
https://www.chasebliss.com/mood-mkii

**Comment by ArislanShiva** [comment]
FYI, we updated the request guidelines:

> New releases from all popular builders (BOSS, EHX, Walrus, TC, EQD, Electro-Harmonix, Wampler, MXR, Chase Bliss, Catalinbread, JHS, DBA, OBNE, etc) are added automatically. There is no need to make a request for those.
