### ISSUE TITLE
 Added Stomp Audio Labs Octopus #1384 - can't see it in the Playground?

### ISSUE THREAD

**Issue by jjtguitar** [PedalPlayground/PedalPlayground.github.io#1480]
I added Stomp Audio Labs Octopus, added the info and images as specified in the contributing info. The request was (I think) approved and merged two weeks ago, but the pedal I added does not appear in the Playground. I checked the json file, and the pedal is there. Not sure if there is something I need to do to make it appear in the list of pedals?

**Comment by ArislanShiva** [comment]
The build failed during deployment.  No fault of yours.  Just wait until @tehtrav pushes the next round and your stuff should go through.

**Comment by jjtguitar** [comment]
Hi, I see the new build is up, and the Stomp Audio Labs Octopus is showing up in the list, but when I add pedal, the image doesn't show up? The object I think is there, because the outline of the pedal is there, and I can select it, move it and delete it, but the image doesn't work.

**Comment by jjtguitar** [comment]
Thanks, I've noticed that some other pedals are having the same issue. LR
Baggs Align Delay, Reverb & Session acoustic pedals, Neural DSP Quad
Cortex, Pirate MIDI Bridge 6, Origin Effects Cali76 Compact Deluxe are ones
that I have been using that have missing images also.

**Comment by ArislanShiva** [comment]
Yeah, one of the other contributors has been changing file names, there are a number that have been broken.

Thanks for pointing those out!  Let me know if you find any more.

**Comment by jjtguitar** [comment]
Every pedal seems to work now apart from the Stomp Audio Labs Octopus. I've checked that the images are in the correct folders, and they are.
