### ISSUE TITLE
Pedal Request: Peterson Strobostomp Mini

### ISSUE THREAD

**Issue by AtomicTones** [PedalPlayground/PedalPlayground.github.io#1508]
Peterson Strobostomp Mini
W: 1.8"
H: 3.7"
<img width="289" alt="Screenshot 2023-05-03 at 1 03 36 AM" src="https://user-images.githubusercontent.com/112257226/235836294-660751cb-ad42-45b5-8180-fbeade75a318.png">

**Comment by ArislanShiva** [comment]
Was added in #1435 and is already active on the site.
