### ISSUE TITLE
Pedal Request: Jackson Audio New Wave (Vice)

### ISSUE THREAD

**Issue by rvarques** [PedalPlayground/PedalPlayground.github.io#1536]
Would love to have this option available:

Jackson Audio New Wave (Vice Version)

Dimensions: 2.7" x 5.13"

![Jackson Audio New Wave Vice](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/89112562/1723bcf1-6979-4dff-8fa8-1d39dd580586)

**Comment by ArislanShiva** [comment]
> We're sorry, but please no requests for alternate colorways.
