### ISSUE TITLE
Pedal Request: Blackhawk Amplifiers Balrog Distortion

### ISSUE THREAD

**Issue by tashiattack** [PedalPlayground/PedalPlayground.github.io#1546]
**Brand:** Blackhawk Amplifiers 
**Model:** Balrog Distortion (Copper Hammertone)
**Size:** 2.6 x 5

![balrog-distortion-v3 jpg copy](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/110792776/e483b85c-c30b-4cfe-affd-71ce78e7c84f)

**Comment by ArislanShiva** [comment]
> We're sorry, but please no requests for alternate colorways
