### ISSUE TITLE
Pedal Request: Idiotbox effects Power Drive

### ISSUE THREAD

**Issue by tashiattack** [PedalPlayground/PedalPlayground.github.io#1550]
Brand: Idiotbox effects
Model: Power Drive
Size: 2.6 x 5

![pknae7tjcetix5mhbohc](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/110792776/51b6e273-05bd-498d-81f4-5bb40138d09a)
![pnxh3cqugojn4mex9kms](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/110792776/92d8c5bd-9449-4aa6-ad0d-fd376acda1a4)

**Comment by ArislanShiva** [comment]
> Post one issue for each pedal you're requesting and do not bump/repost open issues

This was already requested in #1337.  Please delete.

Looks like you need to review [the guidelines for pedal requests](https://github.com/PedalPlayground/PedalPlayground.github.io#requesting-pedals).
