### ISSUE TITLE
Pedal request please : FORMULA B Supa Tank

### ISSUE THREAD

**Issue by KTcentral** [PedalPlayground/PedalPlayground.github.io#1553]
Can you add this pedal please ?
FORMULA B Supa Tank
Height 5,51 inches
Width 3,15 inches

![243116887-028ecc29-d592-46c0-8c39-57b11e56a671](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/135453163/0991ea4f-2368-476e-9857-d94dfb8ca80d)

**Comment by ArislanShiva** [comment]
> Post one issue for each pedal you're requesting and **do not bump/repost open issues**

Please delete this issue.
