### ISSUE TITLE
Pedal Requests : Warwick Tres 3.3 pedalboard, Musicomlab Parallellizer, Cioks DC10 Link, SS/BS mini silver, Pladask Elektrisk Fabrikat w/ Gold Faceplate

### ISSUE THREAD

**Issue by virrrrr** [PedalPlayground/PedalPlayground.github.io#1570]
Tres 3.3: 

Dimensions:  722 mm (W) / 28 27/64"
                     236 mm(D) / 9 19/64"

--

Musicomlab Parallellizer:

 Dimensions : 160(W) x 96(D) mm
                       6.3(W) x 3.8(D) inches

You have the SSBS and Pladask ones already.

![tres3 3](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/123136924/ced155f8-6430-4d8a-9d25-e1c5a36efaa8)

**Comment by ArislanShiva** [comment]
> We're sorry, but please no requests for alternate colorways.
