### ISSUE TITLE
Pedal Request: Effectrode TF-3A Mercury Fuzz

### ISSUE THREAD

**Issue by maphenry** [PedalPlayground/PedalPlayground.github.io#1579]
Dimensions 5.06 x 3.75 including top jacks and switch
![effectrodetf3amercury](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/139550705/a2a82e67-d6d1-48af-bba2-c9912f3b48a0)

**Comment by ArislanShiva** [comment]
This one has already been requested, please delete.
