### ISSUE TITLE
Please add MONO Pedalboard Rail

### ISSUE THREAD

**Issue by thecleantone** [PedalPlayground/PedalPlayground.github.io#1597]
Please help to add the new MONO Pedalboard Rail range of products.

Small: https://monocreators.com/products/pedalboard-rail-small-black-and-stealth-club-accessory-case-black
18” x 13.3” x 3.7” (45.5 x 33.9 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-S-BLK-BDL_2FPFX-PBR-S-BLK-BDL_1688956896984.jpg

Medium: https://monocreators.com/products/pedalboard-rail-medium-black-and-stealth-tour-accessory-case-black
24” x 14.4” x 3.7” (60.8 x 36.7 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-M-BLK-BDL_2FPFX-PBR-M-BLK-BDL_1688957021974.jpg

Large: https://monocreators.com/products/pedalboard-rail-large-black-and-stealth-pro-accessory-case-black
32” x 16.7” x 3.7” (80.9 x 42.4 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-L-BLK-BDL_2FPFX-PBR-L-BLK-BDL_1688613655484.jpg

Problem may be though that the brand hasn't utilised any photos of the products that are directly top down.

**Comment by ArislanShiva** [comment]
It's a pretty simple design and they gave measurements for the rails, so this should be doable w/o photos.
