### ISSUE TITLE
Pedal request: Electronic Audio Experiments - Sending V2

### ISSUE THREAD

**Issue by Lebboht** [PedalPlayground/PedalPlayground.github.io#1614]
![ElectronicAudioExperiments_Sending-V2_01](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/120526906/bcc0b6a3-9ef6-4bae-be79-b178753a1cbe)
 
Thanks in advance!

**Comment by ArislanShiva** [comment]
Was already added in #1502. Please wait for that build to be deployed.
