### ISSUE TITLE
Request: Hudson Broadcast Dual Regent Sounds Sand Yellow, EQD Plumes Found Sound “Green on Green,” Hotone Skyliner series (Krush)

### ISSUE THREAD

**Issue by GreenSky91** [PedalPlayground/PedalPlayground.github.io#1615]
Requesting several pedals which I’d like to add to my pedalboard, two of which are already in the database but in different color ways. The third one is out of print, but I couldn’t resist and snagged one on Reverb :) Thanks in advance!

![IMG_6523](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/132704999/1d122a00-7764-4d6d-aa9c-d80d966c6e8f)
Hudson Electronics Broadcast Sand Yellow

**Comment by GreenSky91** [comment]
EGD Plumes Green on Green

**Comment by GreenSky91** [comment]
![IMG_6527](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/132704999/258dbda4-a826-4afd-9213-9838e3e1747f)
Hotone Krush

**Comment by ArislanShiva** [comment]
> Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests,
