### ISSUE TITLE
Pedalboard Request: MONO Pedalboard Rail

### ISSUE THREAD

**Issue by sarahkydnc** [PedalPlayground/PedalPlayground.github.io#1625]
**MONO Pedalboard Rail Small**
Specs: https://monocreators.com/products/pedalboard-rail-small-black-and-stealth-club-accessory-case-black
![PFX-PBR-S-BLK-BDL_05](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/95635116/102aabbf-1f4e-4e10-8982-3a0296f04fa3)

**MONO Pedalboard Rail Medium**
Specs: https://monocreators.com/products/pedalboard-rail-medium-black-and-stealth-tour-accessory-case-black
![PFX-PBR-M-BLK-BDL_05](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/95635116/e7bf2d16-9650-4956-b20e-f436ce134b5a)

**MONO Pedalboard Rail Large**
Specs: https://monocreators.com/products/pedalboard-rail-large-black-and-stealth-pro-accessory-case-black
![PFX-PBR-L-BLK-BDL_05](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/95635116/9faebee4-a5dc-4a07-a67a-5db7ed0c34e3)

**Comment by ArislanShiva** [comment]
This has already been requested and added to #1502.  Please wait for it to get deployed.  Thanks.
