### ISSUE TITLE
Where is the list of major builders from which products are "automatically added"?

### ISSUE THREAD

**Issue by gnunchucks** [PedalPlayground/PedalPlayground.github.io#1631]
UA just released a few smaller/simpler pedals in more traditional housings today, I was going to submit something to add them, but I saw this line in the readme:

> New releases from all major builders are added to the database automatically -- there is no need to make a request for those,

Probably missing something obvious, but can you point me to that, or perhaps link from the readme? UA wasn't making guitar pedals much before their amp recreations, so I'm not sure if they would be tracked. I see people adding the previous UA pedals in the commit history, but I wanted to make sure I wasn't doing redundant additions.

**Comment by ArislanShiva** [comment]
Any brand with any kind of following will be automatically added.  The only ones we need requests for are obscure builders or older pedals that have slipped thru the cracks.

**Comment by gnunchucks** [comment]
Is that manually tracked by the maintainers or a component in this repo I'm missing?

**Comment by ArislanShiva** [comment]
Manually tracked from social feeds.

**Comment by gnunchucks** [comment]
Cool, and I see the orion in what you linked, much appreciated.
