### ISSUE TITLE
Pedal Request: Pedal Pawn Fuzz (Germanium)

### ISSUE THREAD

**Issue by bduce81** [PedalPlayground/PedalPlayground.github.io#1633]
Pedal Pawn Fuzz (Germanium)
Dimensions = 2.625" (width) x 4.375" (height)

Thank you!

![Pedal Pawn Fuzz (Germanium)](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/143022616/c7ff4526-655d-4c85-8b85-ebab28204156)

**Comment by ArislanShiva** [comment]
Pedal Pawn pedals were all added in #1502, they just haven't been deployed yet.
