### ISSUE TITLE
Pedal request：NUX Trident and NUX 6ixty 5ive overdrive

### ISSUE THREAD

**Issue by fcdld** [PedalPlayground/PedalPlayground.github.io#1638]
NUX Trident:

12.28" * 6.45"
<img width="905" alt="Trident" src="https://github.com/PedalPlayground/PedalPlayground.github.io/assets/42763731/32abfe5f-b64b-444f-b525-3bb1ea799c85">

NUX 6ixty 5ive Overdrive
4.76" * 3.03"

![6ixty5ive-1](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/42763731/5531437d-ac26-44c9-9739-3f1521de6e86)

Thank you!

**Comment by ArislanShiva** [comment]
Both of these were added in #1502
