### ISSUE TITLE
Custom Tones TWE-1

### ISSUE THREAD

**Issue by Winzzy** [PedalPlayground/PedalPlayground.github.io#164]
4.4" x 2.4"

![Custome Tones TWE-1](https://user-images.githubusercontent.com/55894113/65793138-08876100-e11a-11e9-966e-6d8e4291fbb1.png)

The pedal is used by Pete Thorn and has had several glowing reviews on youtube.  I am sure it would be a great one to have in the builder.

**Comment by tehtrav** [comment]
This has been added! Thanks!
