### ISSUE TITLE
Pedal Request: Hotone Ampero Mini

### ISSUE THREAD

**Issue by rvarques73** [PedalPlayground/PedalPlayground.github.io#1663]
Hello, would love to have this pedal.

I requested it and it was closed. However, the pedal was never added. 

Dimensions: 5.28 (W) x 4.72 (D) x 1.92 (H)

![IMG_4501](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/145303053/435f62bb-281a-4aed-b425-9a0df2bf9d01)

**Comment by ArislanShiva** [comment]
The last build was not deployed.  Please stay patient.
