### ISSUE TITLE
Pedal Request: Daredevil Pedals line

### ISSUE THREAD

**Issue by supshiniw** [PedalPlayground/PedalPlayground.github.io#1666]
Pedals include:
Ten Tone Anniversary Fuzz
ACES Hybrid Amplifier
Bootleg Dirty Delay
Silver Solo Silicon Boost
Daisho Earl Slick Fuzz Octave
Real Cool Fuzz
Atomic Cock Fixed Wah
Hype Boost
Cocked & Fearless
Drive-Bi Dual Gain Distortion
Northern Creeper Fuzz
Premium Overdrive
Almighty Bass Fuzz

**Comment by ArislanShiva** [comment]
These were added in #1502, please wait for that build to be deployed.  Thanks.
