### ISSUE TITLE
Pedal Request: Keeley Noble Screamer

### ISSUE THREAD

**Issue by jfmguitarist** [PedalPlayground/PedalPlayground.github.io#1669]
Keeley Noble Screamer

70mm x 127mm

![Keeley Nobel Screamer](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/101024313/79a53647-a292-42f1-8129-61bdb8e1ee8f)

**Comment by ArislanShiva** [comment]
> New releases from all major builders are added to the database automatically -- there is no need to make a request for those,
