### ISSUE TITLE
Pedal Request: Friedman IR-X

### ISSUE THREAD

**Issue by gnunchucks** [PedalPlayground/PedalPlayground.github.io#1672]
This is a different one so even though you have other Friedman pedals, just wanted to double check.

Dimensions (Including Knobs): 5.5” (D) x 6.5” (W) x 2.3 (H)
![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/9288730/ca2b151e-128a-4447-97f3-e76c554bb360)

Also at what cadence is this deployed? The UA pedals were committed a long time ago, but I don't see them on the site yet.

Thanks!

**Comment by gnunchucks** [comment]
Here's the launch special edition colorway too:
![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/9288730/7405b7f9-bb37-42f1-938b-5c9ff7662814)

**Comment by ArislanShiva** [comment]
This was added yesterday in #1609
