### ISSUE TITLE
Pedal Request: Friedman IR-X

### ISSUE THREAD

**Issue by SzaboWabo** [PedalPlayground/PedalPlayground.github.io#1673]
<img width="928" alt="Screenshot 2023-09-29 at 11 10 39 AM" src="https://github.com/PedalPlayground/PedalPlayground.github.io/assets/131698484/9e432ee1-ac3d-4549-813e-916ae7335a44">
![IR-X-large](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/131698484/1ccfe0c4-a178-434d-a163-0c9b7768319b)

6.5" x 5.5"

Thanks!

**Comment by SzaboWabo** [comment]
Awesome, thank you for adding this! I’m new to Github…refreshing my browser isn’t making the changes appear. Is there more I need to do? If there’s a tutorial somewhere, a link to it would be fine and I can take it from there. Thanks!

-Rob

**Comment by SzaboWabo** [comment]
I think I figured it out. Download Github Desktop? Thanks!

-Rob

**Comment by ArislanShiva** [comment]
They build needs to be deployed before the pedal will show up on the site.
