### ISSUE TITLE
Pedal Request: Friedman IR-X CS

### ISSUE THREAD

**Issue by jfmguitarist** [PedalPlayground/PedalPlayground.github.io#1680]
5.5”  x 6.5” 
![friedman-ir-x-cs](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/101024313/4e356a89-af4e-4a95-b122-bdd7bcc92ac0)

**Comment by ArislanShiva** [comment]
> Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests,

**Comment by jfmguitarist** [comment]
OK, but this is a pretty major manufacturer, and I would like my virtual board to look like my real board

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jfmguitarist** [comment]
it may also be worth noting that the difference between the Standard and Custom Shop versions is not just color scheme... the knobs are significantly physically different as well.
