### ISSUE TITLE
Pedal Request: Keeley Super AT Mod Overdrive

### ISSUE THREAD

**Issue by jfmguitarist** [PedalPlayground/PedalPlayground.github.io#1681]
113mm x 65mm
![Keeley-Super-AT-Mod](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/101024313/b94e3e07-65be-47d4-9ee4-343cfa4b7073)

**Comment by ArislanShiva** [comment]
> New releases from all major builders are added to the database automatically -- there is no need to make a request for those,

**Comment by jfmguitarist** [comment]
fair enough with regard to the IR-X and the Noble Screamer…. but I’ve waited about a year for the Super AT Mod Overdrive by Keeley, and it is still not on there, so at what point is it fair play to request a pedal from a major manufacturer?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArislanShiva** [comment]
It was already added in #1502 but that build isn't live on the site yet.  Please remain patient.
