### ISSUE TITLE
Pedal Request: Fender Tone Master Pro

### ISSUE THREAD

**Issue by indieman11** [PedalPlayground/PedalPlayground.github.io#1685]
![Fondo de “18524198_800” eliminado](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/148352408/3bb1e68f-03a1-421b-9503-c2b49f9ccc3e)

**Comment by ArislanShiva** [comment]
This was already added in #1609. Please wait for that build to be deployed, thanks.
