### ISSUE TITLE
Pedal Request: Damnation Audio MBD-2

### ISSUE THREAD

**Issue by fingerstrong** [PedalPlayground/PedalPlayground.github.io#1686]
![damnation-mbd-2_2000x](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/148522208/f42708dc-9f45-4071-b883-4d1768c3c3c0)
Dimensions 2.5w x 4.725h x 2.25d

**Comment by ArislanShiva** [comment]
This is already in the database.

**Comment by fingerstrong** [comment]
Is it in a yet to be released patch or something? There isn't any Damnation Audio pedals available on the site.

**Comment by ArislanShiva** [comment]
Yeah, it was added back in #1502.  That build still hasn't been deployed yet.
