### ISSUE TITLE
Pedal Request: Joyo D-SEED II 

### ISSUE THREAD

**Issue by Artheius** [PedalPlayground/PedalPlayground.github.io#1689]
![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/102348380/7ebdf0b7-503d-440e-bdc3-4b0b9fb4943a)

<html>
<body>

Dimensions: | 105x46x105mm
-- | --

</body>
</html>

**Comment by ArislanShiva** [comment]
This was added awhile back but hasn't been deployed yet.
