### ISSUE TITLE
Please Add the When the Sun  Explodes in White (Thank you!!!)

### ISSUE THREAD

**Issue by anonymouskyleguy** [PedalPlayground/PedalPlayground.github.io#1694]
https://www.beautifulnoiseeffects.com/shop/p/when-the-sun-explodes

As shown here: https://www.littleboxeffects.com/product/beautiful-noise-when-the-sun-explodes

Please let me know if you need an image for this as I have one that should work well but remember it being hard to find. Thanks!

**Comment by ArislanShiva** [comment]
> Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests,

**Comment by anonymouskyleguy** [comment]
My apologies. I wasn’t aware. Thanks for the awesome playground!
