### ISSUE TITLE
Please Add the Laser Engraved Edition Cali76 Stacked Edition (Thank you!!!)

### ISSUE THREAD

**Issue by anonymouskyleguy** [PedalPlayground/PedalPlayground.github.io#1695]
https://origineffects.com/product/cali76-stacked-edition/

Please let me know if you need an image for this as I have one that should work well but remember it being hard to find. Thanks!

**Comment by ArislanShiva** [comment]
> Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests,

**Comment by anonymouskyleguy** [comment]
My apologies. I wasn’t aware. Thanks for the awesome playground!
