### ISSUE TITLE
Please add the ThorpyFX The Dane MKII

### ISSUE THREAD

**Issue by craigwj75** [PedalPlayground/PedalPlayground.github.io#1698]
Dimensions - 2.56 x 4.92
![Thorpy FX Dane MK2](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/148989140/6996aff9-e404-46dd-b306-095718de7f03)

**Comment by ArislanShiva** [comment]
This was added in #1609 but that build hasn't been deployed yet.
