### ISSUE TITLE
Gamechanger Audio Plasma Pedal

### ISSUE THREAD

**Issue by GitFiddler** [PedalPlayground/PedalPlayground.github.io#180]
[Gamechanger Audio Plasma Pedal](https://www.gamechangeraudio.com/wp-content/uploads/2018/03/PLASMAPedal1-2.jpg)
 5.1" X 3.8" X 2.8

**Comment by tehtrav** [comment]
This has been added. Note that I guestimated on the depth of the pedal because the dimensions you gave me seemed to short. Let me know if you have a more accurate measurement. Thanks!
