### ISSUE TITLE
GFI System Synesthesia

### ISSUE THREAD

**Issue by GitFiddler** [PedalPlayground/PedalPlayground.github.io#184]
[GFI System Synesthesia](https://cdn.shopify.com/s/files/1/0045/7952/products/GFISystem-Synesthesia-HeroPlain_1024x1024.png?v=1575514685)
4.72" X 4.72"
This is a new dual engine multi modulation pedal from GFI.

**Comment by tandrewnichols** [comment]
@tehtrav This is in there. Maybe this was never closed?
