### ISSUE TITLE
Electro-Harmonix Mod 11

### ISSUE THREAD

**Issue by najeebfaz95** [PedalPlayground/PedalPlayground.github.io#187]
![mod-11](https://user-images.githubusercontent.com/59372071/71595579-2f20c200-2b77-11ea-884d-440fbf9cdb7d.png)

**Comment by najeebfaz95** [comment]
Dimensions (L x W x H): 2.75" x 4.5" x 2.1"

**Comment by tehtrav** [comment]
@najeebfaz95 just added this in the last commit. Thanks for following the issue guidelines! 👍
