### ISSUE TITLE
Pedal Request: 1981 Inventions DRV (Greyscale)

### ISSUE THREAD

**Issue by rockrockrokk** [PedalPlayground/PedalPlayground.github.io#1991]
1981 Inventions DRV (Greyscale) (3.7in x 4.58in)
![1981 DRV Greyscale](https://github.com/user-attachments/assets/d9ce554a-f340-4de2-9a6b-858e79bd0c70)

**Comment by ArislanShiva** [comment]
As per the request guidelines we are not accepting requests for alternate colorways.

Please close this issue, thanks.
