### ISSUE TITLE
EHX Octavix

### ISSUE THREAD

**Issue by JC-Coolman** [PedalPlayground/PedalPlayground.github.io#204]
Dimensions: 2.75"W  x  4.5"D  x  2.1"H
Jacks: In - Right side / Out - Left side / 9vDC - Rear

https://www.ehx.com/products/octavix

![OCTAVIX-large](https://user-images.githubusercontent.com/63915036/79641010-ebbc8480-8162-11ea-8ee7-d4fb6fa4e27a.jpg)

**Comment by tehtrav** [comment]
Added!
