### ISSUE TITLE
Seymour Duncan 805 Overdrive

### ISSUE THREAD

**Issue by qwertBarney** [PedalPlayground/PedalPlayground.github.io#205]
Dimensions: 2.75"W x 4.5"D x 2.1"H
Jacks: In - Top Right / Out - Top Left / 9vDC - Top, in between input/output jacks

https://www.seymourduncan.com/pedal/805-overdrive

![805-Front-910x1155](https://user-images.githubusercontent.com/64344246/80297779-fd340b00-87b8-11ea-9f26-a8dcb0cced9f.jpg)

**Comment by XlosVSM** [comment]
Already in
