### ISSUE TITLE
Add Eventide Pitchfactor

### ISSUE THREAD

**Issue by Ruliche** [PedalPlayground/PedalPlayground.github.io#230]
Same dimensions as Timefactor/Modfactor/Space
Photo can be found here: https://www.eventideaudio.com/products/stompboxes/pitch-delay/pitchfactor

**Comment by tehtrav** [comment]
Added!

**Comment by Ruliche** [comment]
Thanks Travis! :) Love PBP

Kind regards,
Rodrigo.
