### ISSUE TITLE
Add Walrus Eb-10 EQ & Boost

### ISSUE THREAD

**Issue by thomasdeeross** [PedalPlayground/PedalPlayground.github.io#233]
Could you add the Walrus Eb-10?
Image here: https://www.sweetwater.com/store/detail/EB10Blk--walrus-audio-eb-10-preamp-eq-boost-pedal-black

**Comment by tehtrav** [comment]
The EB-10 has been added. The dimensions on Sweetwater didn't seem right so I am assuming it is the same size as a 1590BB like the EHX Micro Pog.

**Comment by thomasdeeross** [comment]
Amazing, the dimensions you used are perfect!
Thank you so much.
