### ISSUE TITLE
Request to add the original Flashback x4

### ISSUE THREAD

**Issue by ImDeko** [PedalPlayground/PedalPlayground.github.io#236]
Request to add the original Flashback x4. Dimensions are 13 x 7 x 4.

Here's a high res image: 
https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRgY9rbvYKAqw40kcGpAzXT1PeUvcSXVoTQjXziCVisj17MiIo8IwZTZ7rHrtE8HiXw1CYJhPXF5sb0tWhEzShxlzKHh51I

**Comment by tehtrav** [comment]
Just added this. I believe the dimensions you supplied are not quite right but I followed another X4 that seems to have the right dims.
