### ISSUE TITLE
Please add!!!

### ISSUE THREAD

**Issue by Ion-bit** [PedalPlayground/PedalPlayground.github.io#242]
Pladask Elektrisk - Feber
Red Panda - Context v2
Red Panda - Bitmap v2
Holeyboard pedalboard new line...

**Comment by tehtrav** [comment]
Please follow the rules for posting issues posted [here](https://github.com/PedalPlayground/PedalPlayground.github.io#requesting-pedals)

- Include a decent resolution image of the pedal (top-down view, white background)
- Include the dimensions, **in inches** (make sure the dimensions are accurate and include jacks and other protrusions)
- Post **one issue for each pedal** you're requesting
