### ISSUE TITLE
Fix Alexander pedal sizes and add new ones

### ISSUE THREAD

**Issue by Gitappi** [PedalPlayground/PedalPlayground.github.io#247]
All the newer Neo Series Alexander pedals should be the following size:
2.6" W x 4.7" H

This applies to all of the following ones currently on your site:
F13 Flanger
History Lesson
Quadrant
Space Race
Syntax Error

Also, please add their newest releases:
Super Ball
https://www.alexanderpedals.com/shop/superball

Sugarcube
https://www.alexanderpedals.com/shop/sugarcube

Marshmallow
https://www.alexanderpedals.com/shop/marshmallow

Radical Delay DX
https://www.alexanderpedals.com/shop/radical-dx

Sky 5000
https://www.alexanderpedals.com/shop/sky5000

Super Neo-Matic
https://www.alexanderpedals.com/shop/neo-matic

Wavelength
https://www.alexanderpedals.com/shop/wavelength

These are also 2.6" W x 4.7" H.

**Comment by ArislanShiva** [comment]
Done
