### ISSUE TITLE
Add Origin Effects Modulation/Overdrive Pedals

### ISSUE THREAD

**Issue by Gitappi** [PedalPlayground/PedalPlayground.github.io#248]
RevivalTrem
https://origineffects.com/wp-content/uploads/2020/05/RevivalTREM-Bias-Tremolo.png
3.66" W x 5.62" H

Magma57
https://origineffects.com/wp-content/uploads/2020/10/Front-scaled.jpg
3.66" W x 5.62" H

**Comment by tehtrav** [comment]
Both have been added!
