### ISSUE TITLE
Add Spaceman Effects pedals

### ISSUE THREAD

**Issue by Gitappi** [PedalPlayground/PedalPlayground.github.io#249]
Gemini IV Fuzz
3.7" W x 4.7" H
https://cdn11.bigcommerce.com/s-dks6ju/images/stencil/1280x1280/products/17144/171812/c9423342-b07a-5c0e-8c41-5978f41eaf06__43536.1562698806.jpg?c=2

Sputnik III Fuzz
3.7" W x 4.7" H
https://cdn.shopify.com/s/files/1/0085/0368/9278/products/sputnik-III-standard-edition-o_2000x.jpg?v=1608051561

Apollo VII Overdrive
2.76" W x 4.72" H
https://cdn.shopify.com/s/files/1/0085/0368/9278/products/apollo-standard-f-o-spaceman.jpg?v=1583453017

Saturn VI Harmonic Booster
2.76" W x 4.72" H
https://cdn.shopify.com/s/files/1/0085/0368/9278/products/saturn-vi-standard-f-o-spaceman_2000x.jpg?v=1583443647

**Comment by ArislanShiva** [comment]
Added
