### ISSUE TITLE
Add Red Panda Context 2 and Bitmap 2

### ISSUE THREAD

**Issue by Gitappi** [PedalPlayground/PedalPlayground.github.io#250]
Context 2
https://cdn11.bigcommerce.com/s-5d662uh/images/stencil/2000x2000/products/77/471/RedPandaLab_Context_Front__80774.1604331453.jpg?c=2

Bitmaps 2
https://cdn11.bigcommerce.com/s-5d662uh/images/stencil/2000x2000/products/85/481/RPL_103V2_front__20398.1611088063.jpg?c=2

Both have the same dimensions as the Tensor:
3.05" W x 4.75" H

**Comment by ArislanShiva** [comment]
Added
