### ISSUE TITLE
Add Jet Pedals Revelation Reverb v2 MIDI

### ISSUE THREAD

**Issue by gtujan** [PedalPlayground/PedalPlayground.github.io#251]
Revelation Reverb v2 MIDI (White)
![RevWhiteFront_82a6c56e-2d58-4eb4-a422-96e2d2506c7b_1664x1664](https://user-images.githubusercontent.com/121795/107328629-fa0cd000-6ae9-11eb-800d-aa2dac5e71d7.png)
3" W x 5" H

Revelation Reverb v2 MIDI (Blue)
![RevBlueFront_abddabab-074f-493f-ad67-bdba396ae551_1664x1664](https://user-images.githubusercontent.com/121795/107328643-fe38ed80-6ae9-11eb-9f9b-af96afde247d.png)

3" W x 5" H

**Comment by tehtrav** [comment]
I added white and purple versions

**Comment by gtujan** [comment]
@tehtrav awesome!
