### ISSUE TITLE
Request 3: Neo Micro Vent 122, Big Muff Pi Ram's Head, MXR MC401 Booster

### ISSUE THREAD

**Issue by tjatomato** [PedalPlayground/PedalPlayground.github.io#281]
EDIT: updated with sizes
They are
**Neo Micro Vent 122**  4.44 x 2.55 x 1.85
![Neo_Micro Vent 122 4 44x2 55x1 85](https://user-images.githubusercontent.com/79944532/109724287-a86ad900-7baf-11eb-89ac-cae3675377f5.png)

Electro Harmonics Ram's Head Big Muff Pi   4.5 x 2.75 x 2.1
![RamsHEad_4 5 x 2 75 x 2 1](https://user-images.githubusercontent.com/79944532/109724288-aa349c80-7baf-11eb-8297-61d61eb9a58d.png)
  
MXR CAE Boost/Line Driver MC401     5.8 x 4.8 x 3.0
![MXR MC 401 CAE Boost_Line Driver 5 8x4 8x3 0](https://user-images.githubusercontent.com/79944532/109724294-ac96f680-7baf-11eb-9728-659715ba5a64.png)

Many thanks in advance

**Comment by ArislanShiva** [comment]
added mxr booster
