### ISSUE TITLE
Create KMA Audio Machines Fuzzly Bear

### ISSUE THREAD

**Issue by PeteCarpenter** [PedalPlayground/PedalPlayground.github.io#289]
![KMA Fuzzly Bear off](https://user-images.githubusercontent.com/80157608/110206627-1b5da380-7e7f-11eb-9881-c144403c5f31.jpg)

Dimensions : 2,40 x 4,45 x 1,22

Thanks a lot

**Comment by ArislanShiva** [comment]
Added
