### ISSUE TITLE
Create MESA High Wire Dual Buffer

### ISSUE THREAD

**Issue by PeteCarpenter** [PedalPlayground/PedalPlayground.github.io#290]
![MESA High Wire Dual Buffer](https://user-images.githubusercontent.com/80157608/110206809-4694c280-7e80-11eb-9991-718dc42c564b.JPG)

Dimensions : 2.48 x 4.48 x2.06 (W x D x H)

Thanks a lot

**Comment by tehtrav** [comment]
Just added the High Wire

**Comment by PeteCarpenter** [comment]
Cheers ! Much appreciated 👍
