### ISSUE TITLE
CREATE Warwick Rockboard Tres 3.0

### ISSUE THREAD

**Issue by topherrrr92** [PedalPlayground/PedalPlayground.github.io#292]
Hey, would someone be able to create a Warwick Rockboard Tres 3.1 pedalboard?

**Comment by andrewmcc1120** [comment]
Width: 20.54
Height: 9.29

![output-onlinepngtools](https://user-images.githubusercontent.com/38885940/110244620-92ea0c00-7f2d-11eb-9a9e-f3f356f17d3e.png)
