### ISSUE TITLE
JOYO PXL-LIVE Switcher

### ISSUE THREAD

**Issue by topherrrr92** [PedalPlayground/PedalPlayground.github.io#297]
Hello, can someone please add a **JOYO PXL LIVE** loop switcher to the list of pedals. Thank you!

Dimensions:

54.1 (x) 6.7 (x) 5.3cm
![joyo-pxl-live](https://user-images.githubusercontent.com/80185447/111000056-3aa07900-8336-11eb-9492-902fe4997548.jpg)

**Comment by tehtrav** [comment]
Added
