### ISSUE TITLE
Holy Grail Nano

### ISSUE THREAD

**Issue by Odeul** [PedalPlayground/PedalPlayground.github.io#298]
Request for Holy Grail Nanon from Electro-Harmonix

Link to a good looking image:
[https://cdn.shopify.com/s/files/1/1699/1203/products/Electro-Harmonix-Holy-Grail-Nano-Reverb-Image-2_720x.jpg?v=1610600547](url)

**Comment by Odeul** [comment]
![Electro-Harmonix-Holy-Grail-Nano-Reverb-Image-2_1400x](https://user-images.githubusercontent.com/80607311/111054485-02369300-843b-11eb-9d0b-3e65edcbf6f1.jpg)

Dimensions: 2.50 x 4.25 x 1.25" (6.4 x 10.8 x 3.2 cm)

**Comment by romaintb** [comment]
Thanks for the bug report :)
I will take care of this when I have a bit of time (should be today).

Cheers !
