### ISSUE TITLE
PettyJohn Rail

### ISSUE THREAD

**Issue by dlcoppess** [PedalPlayground/PedalPlayground.github.io#306]
![rail-pop-pedal-pic_280x420](https://user-images.githubusercontent.com/80791562/111382445-fdf5ba00-8674-11eb-92cb-fca649f1a6da.jpg)

PettyJohn Rail Fuzz
Dimensions: 2.5”W x 4.75”L x 2.5” H

**Comment by tehtrav** [comment]
added!
