### ISSUE TITLE
Electro Harmonix Q Tron Plus

### ISSUE THREAD

**Issue by guusjv** [PedalPlayground/PedalPlayground.github.io#312]
![8C39A0E2-F528-4846-92D1-9DAD5162FBBE](https://user-images.githubusercontent.com/81335940/112398574-d05be100-8d04-11eb-8c48-776d1792a720.jpeg)

size: 6” x 2.4”

**Comment by tehtrav** [comment]
Added

**Comment by guusjv** [comment]
Thank you!
I can’t see it in the website unfortunately... any ideas why?

Verstuurd vanaf mijn iPhone

**Comment by tehtrav** [comment]
try searching q-tron (hyphen included), "qtron" wont work (I'll fix search to be more forgiving at some point)
