### ISSUE TITLE
Champion Leccy "The Fettle Boost"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#313]
Brand: Champion Leccy
Pedal: The Fettle Boost
Dimensions: W: 2.65" H: 4.75"
![fullsizeoutput_52a](https://user-images.githubusercontent.com/81455099/112708950-5e5dd600-8e83-11eb-9479-4691049df495.jpeg)

**Comment by ArislanShiva** [comment]
Added
