### ISSUE TITLE
Champion Leccy "The Woozy"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#314]
Brand: Champion Leccy
Pedal: The Woozy
Dimensions: W: 3.75" H: 4.75"
![WZ-B-V2](https://user-images.githubusercontent.com/81455099/112708981-9fee8100-8e83-11eb-8296-d4fe708dbc8c.jpg)

**Comment by ArislanShiva** [comment]
Added
