### ISSUE TITLE
Champion Leccy "The Skitter"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#315]
Brand: Champion Leccy
Pedal: The Skitter
Dimensions: W: 3.75" H: 4.75"
![SK-K-V2-1](https://user-images.githubusercontent.com/81455099/112709000-c01e4000-8e83-11eb-8eb5-28f3d1eb658b.jpg)

**Comment by ArislanShiva** [comment]
Added
