### ISSUE TITLE
Champion Leccy "The Canny Fettle Boost"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#316]
Brand: Champion Leccy
Pedal: The Canny Fettle Boost
Dimensions: W: 3.75" H: 4.75"
![fullsizeoutput_553](https://user-images.githubusercontent.com/81455099/112709026-e5ab4980-8e83-11eb-98ef-51fd3ec0ca9d.jpeg)

**Comment by ArislanShiva** [comment]
Added
