### ISSUE TITLE
Champion Leccy "The Kilter"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#317]
Brand: Champion Leccy
Pedal: The Kilter
Dimensions: W: 6.15" H: 4.75"
![KT-Y](https://user-images.githubusercontent.com/81455099/112709110-7b46d900-8e84-11eb-9e5e-18063a37c7ba.jpg)

**Comment by ArislanShiva** [comment]
Added
