### ISSUE TITLE
Earthquaker Devices "Aqueduct"

### ISSUE THREAD

**Issue by dtyler5603** [PedalPlayground/PedalPlayground.github.io#318]
Brand: Earthquaker Devices
Pedal: Aqueduct
Dimensions: W: 2.50" H: 4.75"
![Aqueduct-Vibrato](https://user-images.githubusercontent.com/81455099/112709173-f14b4000-8e84-11eb-8d2e-7b6cbbae3fc4.jpg)

**Comment by romaintb** [comment]
Thanks for the suggestion :)
I will take care of this when I have a bit of time (should be today).

Cheers !
