### ISSUE TITLE
Tech21 SansAmp VTBass DI

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#325]
https://www.tech21nyc.com/products/sansamp/vtbass-di/
I can't find the dimensions but the enclosure is a Hammond similar to what is used for the other SansAmp products and to an MXR Carbon Copy Deluxe

![image](https://user-images.githubusercontent.com/81639930/113024341-ecd59e80-9186-11eb-813e-cb37345f68c0.png)

**Comment by XlosVSM** [comment]
Closed in #724
