### ISSUE TITLE
MarkBass Ground Stereo Pre

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#328]
Can't find the dimension but I can measure my copy in a few days

![image](https://user-images.githubusercontent.com/81639930/113027494-70dd5580-918a-11eb-8624-398fddf238f5.png)

**Comment by romaintb** [comment]
@TheTourDad yes, please and thank you :)

**Comment by TheTourDad** [comment]
The dimensions are 235 x 145 mm
Thank you
