### ISSUE TITLE
Keeley Tesla Mk III Soviet Fuzz Bender

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#329]
https://robertkeeley.com/Keeley+Tesla+Mk+III+Soviet+Fuzz+Bender
Dimensions are the same as an MXR phase 90

![image](https://user-images.githubusercontent.com/81639930/113028500-a20a5580-918b-11eb-9c44-b1c7249fe616.png)

**Comment by romaintb** [comment]
Wow, didn't know this existed. Gorgeous one for sure !

**Comment by TheTourDad** [comment]
> Wow, didn't know this existed. Gorgeous one for sure !

I randomly ran into one of those and I'm since the lucky owner of #177 of 200.
Works really well with single coils
