### ISSUE TITLE
JHS Pedals Firefly Fuzz

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#330]
https://www.jhspedals.info/discontinued-and-rare
Same dimensions as a JHS Pink Panther

![image](https://user-images.githubusercontent.com/81639930/113029296-8a7f9c80-918c-11eb-9dd8-8aa5f82fd909.png)

**Comment by tehtrav** [comment]
JHS Firefly has been added!
