### ISSUE TITLE
DigiTech JamMan Stereo

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#332]
https://www.digitech.com/discontinued-products/JAMMAN+STEREO.html?dwvar_JAMMAN%20STEREO_color=Blue-USA-Current&cgid=discontinued-products#start=1

Dimensions: 
6.84” (L) x 6.70” (W) x 2.89” (H)
173.6 mm (L) x 170.1 mm (W) x 73.4 mm (H)

![image](https://user-images.githubusercontent.com/81639930/113029677-fe21a980-918c-11eb-95d5-3659436308ee.png)

**Comment by romaintb** [comment]
Thanks for the suggesting this pedal :)
I will take care of this when I have a bit of time (should be today).

Cheers !
