### ISSUE TITLE
Green Carrot Pedals Infatuator

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#334]
I don't have the exact dimensions but I can measure my copy in a few days

![image](https://user-images.githubusercontent.com/81639930/113049045-7b581900-91a3-11eb-9076-665f4c81c294.png)
![image](https://user-images.githubusercontent.com/81639930/113049078-84e18100-91a3-11eb-9bf6-6b9a3e8477c4.png)

**Comment by romaintb** [comment]
@TheTourDad I will gladly add the pedal, please mesure yours up ;)

**Comment by TheTourDad** [comment]
So I've measured it and the dimensions are 120 x 105 mm
