### ISSUE TITLE
Line6 Relay G30 - please add

### ISSUE THREAD

**Issue by justinjbaugh** [PedalPlayground/PedalPlayground.github.io#340]
Brand: line6
Pedal: G30relay
Dimensions: W: 2.125" H: 4.375"
![line6-g30relay-700px](https://user-images.githubusercontent.com/82021378/113675475-02643000-9681-11eb-91de-6a1fa9ff8ba6.png)
![line6-g30relay-350px](https://user-images.githubusercontent.com/82021378/113675492-07c17a80-9681-11eb-83b6-391ed14ed9c2.png)

**Comment by tehtrav** [comment]
I have just pushed this live. The dimensions above don't seem to be right but I think I got pretty close by using the provided height and extrapolating the width from the photo dimensions.

**Comment by justinjbaugh** [comment]
Thank you! Looks great!
