### ISSUE TITLE
Add Bad Monkey Please

### ISSUE THREAD

**Issue by Jonathan2345778** [PedalPlayground/PedalPlayground.github.io#347]
Brand: Digitech
Pedal Name: Bad Monkey
Height: 5 in
Width: 2 in
![image](https://user-images.githubusercontent.com/82112108/113905511-13e42f80-9788-11eb-96f3-0617f33e6305.png)

**Comment by tehtrav** [comment]
Can't promise the dimensions are perfect but it has been added

**Comment by Jonathan2345778** [comment]
Thanks man
