### ISSUE TITLE
Chase Bliss Gravitas image

### ISSUE THREAD

**Issue by beatleboy121** [PedalPlayground/PedalPlayground.github.io#353]
Gravitas pedal image recently updated with the wrong image. Warped Vinyl has been used incorrectly. Correct Gravitas image attached. 
![chasebliss-gravitas](https://user-images.githubusercontent.com/82910797/115507001-7141ab80-a273-11eb-9375-c2ef8a5b9c6f.png)

**Comment by romaintb** [comment]
Thanks for the bug report :)
I will take care of this when I have a bit of time (should be today).

Cheers !
