### ISSUE TITLE
New Pedal Request: Browne Amplification Protein (White and Black Color Editions)

### ISSUE THREAD

**Issue by msrodrig22** [PedalPlayground/PedalPlayground.github.io#354]
If possible, can you please add the white and black color editions of the Browne Amplification Protein pedal?

Browne Amplification Website: https://browneamps.com/
Browne Amps Protein web page: https://browneamps.com/store/protein-dual-overdrive

Thanks,
Matt Rodriguez

**Comment by romaintb** [comment]
Thanks for the great suggestion. It is a pedal we are seeing more and more.
I will take care of this when I have a bit of time.

Cheers !
