### ISSUE TITLE
AMT WH-1 Japanese Girl Wah

### ISSUE THREAD

**Issue by h4ruk0** [PedalPlayground/PedalPlayground.github.io#377]
![J04530000000000-00-500x500](https://user-images.githubusercontent.com/83532270/116806595-d018e780-aaf3-11eb-9876-8d2c50d8c1df.jpg)
4.33 x 2.45 (should be the same size as the other AMT expression pedals already on the site)

**Comment by romaintb** [comment]
Hey @h4ruk0, thanks for reporting this.
https://amtelectronics.com/new/amt-wh-1/ doesn't seem to mention "Japanese Girl" at all, so I created a pull request naming it "WH-1 Optical WAH-WAH".
Let me know if I missed something ;)
