### ISSUE TITLE
Okko Basstard

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#395]
Enclosure is the same as a Tech21 Blonde 

![image](https://user-images.githubusercontent.com/81639930/117154777-7991fe80-adbc-11eb-853b-286543b6338d.png)

**Comment by romaintb** [comment]
Hey @TheTourDad, it seems we already have this one listed ;)

**Comment by TheTourDad** [comment]
> Hey @TheTourDad, it seems we already have this one listed ;)

Ooops ! My bad.
Sorry.
