### ISSUE TITLE
"Electro Harmonix Big Muff Pi Deluxe" not showing up at all when selected

### ISSUE THREAD

**Issue by h4ruk0** [PedalPlayground/PedalPlayground.github.io#399]
Basically title, not sure why, im not a developer lol

I keep selecting it and clicking "add pedal" and nothing shows up

EDIT: wait, I just noticed, its "there" on the top left corner, its just invisible for some reason

**Comment by romaintb** [comment]
Woopsie, I messed that one up. Thanks for reporting 👍 
(btw, you can remove that "ghost pedal", and try refreshing then adding back the pedal when #409 is merged)
