### ISSUE TITLE
Stone Deaf Fig Fumb Fuzz

### ISSUE THREAD

**Issue by h4ruk0** [PedalPlayground/PedalPlayground.github.io#403]
![13190761_800](https://user-images.githubusercontent.com/83532270/117251584-7887be00-ae0a-11eb-945a-b087e4b0a998.jpg)
Should be about the same size as Warp Drive 
4.01in x 5.98in (102mm x 152mm)

**Comment by romaintb** [comment]
hey @h4ruk0 :)  it seems the fig fumb is already on ppg
