### ISSUE TITLE
Stone Deaf Trashy Blonde

### ISSUE THREAD

**Issue by h4ruk0** [PedalPlayground/PedalPlayground.github.io#404]
![280632-stone_deaf-trashy_blonde-top_preview](https://user-images.githubusercontent.com/83532270/117252066-17acb580-ae0b-11eb-895a-b164365d53e1.jpeg)
4.01in x 5.98in (102mm x 152mm) same size as Warp Drive

**Comment by romaintb** [comment]
we already have that one ;)
