### ISSUE TITLE
Power supplies support

### ISSUE THREAD

**Issue by TheTourDad** [PedalPlayground/PedalPlayground.github.io#413]
It would be nice to have support for power supplies, especially for pedalboards that doesn't have space for those underneath

**Comment by h4ruk0** [comment]
There's a few power supplies on the site already, just look them up like you would look up a pedal

**Comment by TheTourDad** [comment]
Thanks guys!
I'd like to add the Mooer Macro Power S12
The dimensions are 225mm(D)×88mm(W)×50mm(H)

Here's a picture of the power supply:
![image](https://user-images.githubusercontent.com/81639930/119270372-ab002c00-bbfc-11eb-9305-fea374ec014b.png)
