### ISSUE TITLE
Flower Pedals - Dandelion V2

### ISSUE THREAD

**Issue by ConnorHub** [PedalPlayground/PedalPlayground.github.io#423]
I made a mistake when I filed this one last time!! I gave the wrong dimensions, I apologize. Here to rectify my error!

4.75" x 2.5"

![Dandelion2](https://user-images.githubusercontent.com/83631608/117876528-b51b4580-b260-11eb-921c-10875134126a.png)

**Comment by romaintb** [comment]
Don't worry, happens to all of us. Should be fixed soon :)
