### ISSUE TITLE
Pedal request: Decibelics Golden Horse

### ISSUE THREAD

**Issue by Ripley63** [PedalPlayground/PedalPlayground.github.io#459]
Hi,
can you please add Decibelic Golden Horse?
Measures are 4,09 x 1,93

Thanks

![decibelics-golden-horse](https://user-images.githubusercontent.com/85568509/121210968-69b68000-c87c-11eb-9e95-e68818782e2f.jpg)

**Comment by romaintb** [comment]
https://github.com/PedalPlayground/PedalPlayground.github.io/pull/585 adds it, but in black
