### ISSUE TITLE
Pedal Request: 29 Pedals EUNA and Vertex Boost mkii

### ISSUE THREAD

**Issue by clarkstrasburg** [PedalPlayground/PedalPlayground.github.io#467]
![EUNA](https://user-images.githubusercontent.com/34170564/122414920-1c59a300-cf4d-11eb-939a-5d2fa86f32ab.png)
![boostmkii](https://user-images.githubusercontent.com/34170564/122414967-24194780-cf4d-11eb-8cbf-08506162e5eb.png)

**Comment by ArislanShiva** [comment]
Added
