### ISSUE TITLE
Pedal Request: Vertex Boost MKII

### ISSUE THREAD

**Issue by msrodrig22** [PedalPlayground/PedalPlayground.github.io#471]
Pedal Request: Vertex Boost MKII

Just requesting if you can add the following Vertex Boost MKII pedal: https://www.vertexeffects.com/boost-mkii

Dimensions (L x W x H): 4.5” x 2.2” x 1.8”

Thank you for all the great work!

Thanks again,
Matt Rodriguez

**Comment by msrodrig22** [comment]
![Vertex Boost MKII](https://user-images.githubusercontent.com/83134586/124653001-c8b2e900-de6a-11eb-8c50-0c8089977b7f.png)

**Comment by msrodrig22** [comment]
![Vertex Boost MKII](https://user-images.githubusercontent.com/83134586/126565974-8f10b721-708c-446e-b93f-122055cad3de.jpg)

**Comment by msrodrig22** [comment]
I have included another image of the Vertex Boost MKII pedal. This one has a white background and does not have the blue led lit.

**Comment by ArislanShiva** [comment]
Added
