### ISSUE TITLE
HX Stomp Storm Trooper White

### ISSUE THREAD

**Issue by gtujan** [PedalPlayground/PedalPlayground.github.io#474]
![hx_stomp](https://user-images.githubusercontent.com/121795/123769580-060ff780-d8fc-11eb-84b7-0c7b78a30edc.png)

Dimensions L x W x H - 4.96" x 7.01" x 2.6"

**Comment by ArislanShiva** [comment]
Added

**Comment by gtujan** [comment]
awesome!
