### ISSUE TITLE
List of pedals currently blank

### ISSUE THREAD

**Issue by astatum** [PedalPlayground/PedalPlayground.github.io#482]
Hi! Just wanted to let folks know that the list of pedals is currently blank and no options show up either when searching or clicking the drop-down menu. Screenshot attached. This issue occurs on multiple computers, smart phones, and in different browsers. 

![image](https://user-images.githubusercontent.com/39130063/126205283-415d9fcb-c2d2-4624-b279-5a26fc801b3c.png)

**Comment by tehtrav** [comment]
Thanks for the heads up! This should be fixed now.
