### ISSUE TITLE
Pedal Request: Neunaber ILLUMINE

### ISSUE THREAD

**Issue by rvarques** [PedalPlayground/PedalPlayground.github.io#525]
Hi! I'd like to add this pedal:

NEUNABER ILLUMINATE REVERB:

Dimensions: 4.8" x 3.9" (in)

Thanks in advance! 

![ILLUMINE_top_2000x1100_e6ccfdef-e851-406f-a352-c9cf64eccb63_x1100](https://user-images.githubusercontent.com/89112562/129820049-25982e3f-79b9-4fb8-b5e8-820060aded63.jpg)

**Comment by ArislanShiva** [comment]
Added

**Comment by rvarques** [comment]
Thank you so much!
