### ISSUE TITLE
Sennheiser XSW-D Pedalboard

### ISSUE THREAD

**Issue by carminlosanto** [PedalPlayground/PedalPlayground.github.io#595]
![sennheiser_xsw_d_pedalboard_rx_xs_wireless_digital_pedalboard_1444566-removebg-preview](https://user-images.githubusercontent.com/82662106/134176146-1574ddef-f9ff-430c-ab59-66fe41704290.png)

Width: 3.2 inches
Height: 5.1 inches

**Comment by cskindley** [comment]
Should be closed as it’s already added.
