### ISSUE TITLE
TC Wiretapp

### ISSUE THREAD

**Issue by nsnate02** [PedalPlayground/PedalPlayground.github.io#60]
Could you add TC Electronics Wiretapp Riff Recorder 
From manual on TC website dimensions:  (HxWxD) 92x43x50mm (3.6x1.7x2.0")
Image:  https://media63.music-group.com/media/PLM/data/images/products/P0CM1/1800Wx1800H/WIRETAP-RIFF-RECORDER_P0CM1_Top_L.png

**Comment by tehtrav** [comment]
Added
