### ISSUE TITLE
Fender FVP-1

### ISSUE THREAD

**Issue by nsnate02** [PedalPlayground/PedalPlayground.github.io#61]
Please add A Fender FVP-1 pedal
Dimensions from Amazon: Dimensions: 8.4"L x 3.5"W x 2.6"H
Image: https://images.reverb.com/image/upload/s--LPHFwoRF--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1483718620/dgqdgqc2cd2ijdm5lkdv.jpg

**Comment by tehtrav** [comment]
This has been added but I'm not 100% sure the dimensions are correct. If you have one and feel like measuring it please let me know what you get.
