### ISSUE TITLE
Pedal Request(s) : Union Tube & Transistor pedals. 

### ISSUE THREAD

**Issue by Mattcampbell96** [PedalPlayground/PedalPlayground.github.io#642]
Hey PedalPlayground Team! 

I'd love to see the Union Tube & Transistor pedals added to the rendering.. Attached are the Sona Bender, Tour Bender, More, LAB, and Bumble Buzz. All pedals measure the same 3.7x4.82 roughly.

![union_sone_bender](https://user-images.githubusercontent.com/84297949/138396432-a93b8c71-ed77-4b10-a78b-fd415e35124b.jpg)
![union_tour_bender](https://user-images.githubusercontent.com/84297949/138396434-fbae00f6-4d0c-4055-84f8-ccc567370b59.jpg)

![union_more](https://user-images.githubusercontent.com/84297949/138396437-3842f8e2-4fe9-459f-8ae6-c6f5b780bce2.jpg)
![FullSizeRender+(2)](https://user-images.githubusercontent.com/84297949/138396447-f02901c1-f505-4898-b748-cbdcd56bb13c.jpg)
![bumble_buzz_front_1](https://user-images.githubusercontent.com/84297949/138396452-6869f23d-d558-4052-a41d-434542693162.jpg)

**Comment by XlosVSM** [comment]
No good photo of LAB so not included in my pull request
