### ISSUE TITLE
Walrus Audio Fathom Reverb

### ISSUE THREAD

**Issue by anthonyjinciong** [PedalPlayground/PedalPlayground.github.io#74]

**Comment by ZiPan77** [comment]
[Walrus Audio Fathom Multi-function Reverb Pedal](https://www.sweetwater.com/store/detail/Fathom--walrus-audio-fathom-multi-function-reverb-pedal) measures 1.39" x 	2.6" x 4.77"

**Comment by RadFranz** [comment]
![immagine](https://user-images.githubusercontent.com/35343114/54841902-b67c0380-4cd0-11e9-8a5e-b5b65e48574d.png)

**Comment by tehtrav** [comment]
Closing out as this has been added a while ago. Thanks!
