### ISSUE TITLE
Pedal Request: TC Electronic SCF Gold Chorus/Flanger

### ISSUE THREAD

**Issue by snurth** [PedalPlayground/PedalPlayground.github.io#759]
3,7" x 5"
![Skærmbillede 2022-01-18 kl  19 21 42](https://user-images.githubusercontent.com/97981015/149996732-13e80203-05a6-4347-8707-68e3d269f632.png)

**Comment by djpgreek** [comment]
I added this today

**Comment by djpgreek** [comment]
Hi Travis,

Just wondering if I submitted wrong or not? I put these two pedals in to contribute a couple of weeks ago and don’t see them in the system. I’d like to start contributing, but want to do it right?

Best
Dimitri
