### ISSUE TITLE
Add Xotic RC Booster V2

### ISSUE THREAD

**Issue by menickm1** [PedalPlayground/PedalPlayground.github.io#76]
https://images.reverb.com/image/upload/s--C80FQjg3--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1476900315/rjst6cxtczekrmhqfa9q.jpg
Dimensions are 4.39" x 2.38" x 1.98" (110mm X 60mm X 50mm)

**Comment by tehtrav** [comment]
Added
