### ISSUE TITLE
Electro-Harmonix Big Muff variants

### ISSUE THREAD

**Issue by Freddyr91** [PedalPlayground/PedalPlayground.github.io#79]
Electro-Harmonix GREEN RUSSIAN BIG MUFF
Electro-Harmonix Op-Amp Big Muff Pi
Electro-Harmonix Nano Big Muff Pi

**Comment by ZiPan77** [comment]
[Electro-Harmonix GREEN RUSSIAN BIG MUFF](https://www.sweetwater.com/store/detail/RussianBigMuff--electro-harmonix-green-russian-big-muff-pi-fuzz-pedal) measures 4.5" x 2.75" x 2"
[Electro-Harmonix Op-Amp Big Muff Pi](https://www.sweetwater.com/store/detail/OpAmpBigMuff--electro-harmonix-op-amp-big-muff-pi-fuzz-pedal) measures 4.5" x 2.75" x 2"
[Electro-Harmonix Nano Big Muff Pi](https://www.sweetwater.com/store/detail/NanoBigMuff--electro-harmonix-nano-big-muff-pi-distortion-fuzz-overdrive-pedal) measures 4.5" x 2.75" x 2"

**Comment by tehtrav** [comment]
Added by @apeekaboo !
