### ISSUE TITLE
JHS Pedals to Add

### ISSUE THREAD

**Issue by ZiPan77** [PedalPlayground/PedalPlayground.github.io#80]
[JHS Unicorn V2](https://www.jhspedals.info/unicorn-v2) measures 2.2"x4.8"x1.6"
[JHS Twin Twelve V2](https://www.jhspedals.info/twin-twelve-v2) measures 2.2"x4.8"x1.6"
[JHS Spring Tank Reverb](https://www.jhspedals.info/spring-tank) measures 2.6"x4.8"x1.6"
[JHS Crayon](https://www.jhspedals.info/crayon)  measures 2.6"x4.8"x1.6"
[JHS Colour Box V2](https://www.jhspedals.info/colour-box-v2) measures 3.65"x4.65"x1.2

**Comment by gyeniceri** [comment]
JHS AT+ measures (I have no idea)

**Comment by ZiPan77** [comment]
[JHS AT+ measures](https://www.jhspedals.com/wp-content/uploads/2018/01/JHS-AT-top-Web.jpg) 2.2"x4.8"x1.6"

**Comment by tehtrav** [comment]
These have all been added
