### ISSUE TITLE
TheGigRig Pedals to Add

### ISSUE THREAD

**Issue by ZiPan77** [PedalPlayground/PedalPlayground.github.io#81]
[QuarterMaster QMX - 2](https://shopusa.thegigrig.com/copy-of-quartermaster-qmx-4/) measures 6.30in x 1.57in x 2.28in
[QuarterMaster QMX - 6](https://shopusa.thegigrig.com/quartermaster-qmx-6/) measures 16.14in x 1.57in x 2.28in
[QuarterMaster QMX - 10](https://shopusa.thegigrig.com/quartermaster-qmx-10/) measures 26.77in x 1.57in x 2.28in
[ABY-BABY](https://shopusa.thegigrig.com/aby-baby/) measures 6.3in x 1.57in x 2.28in

**Comment by Benjamin-RM** [comment]
Issue to log: 

QMX 2 added has been inserted twice, at the scale of the QMX 4 - while also overwriting it.
