### ISSUE TITLE
Pedalboard Request: Fender Pedalboards Small, Medium & Large

### ISSUE THREAD

**Issue by rvarques** [PedalPlayground/PedalPlayground.github.io#867]
Hi! Would love to have these Fender pedalboards added:

Dimensions:

Small - W 18” x D 12.8” x H 2.95”

![Fender Pedalboard Small](https://user-images.githubusercontent.com/89112562/158596454-89dfc9c8-671f-45fd-8b70-7bd8ae1e91df.jpg)

Medium - W 24” x D 12.8” x H 2.95”

![Fender Pedalboard Medium](https://user-images.githubusercontent.com/89112562/158596498-746d17ca-039b-42c8-a6ca-13b1fe5e4e5a.jpg)

Large - W 32” x D 16” x H 2.95”

![Fender Pedalboard Large](https://user-images.githubusercontent.com/89112562/158596519-5ab0951f-9f81-4033-9a03-2509cb1f96f3.jpg)

Thanks in advance!

**Comment by ArislanShiva** [comment]
This has already been requested and closed.
