### ISSUE TITLE
Pedal Request

### ISSUE THREAD

**Issue by grgbikas** [PedalPlayground/PedalPlayground.github.io#899]
Brand : Way Huge
Model : Pork & Pickle Smalls Bass Overdrive
Dimension : 
Height = 1.75"
Width  =	2.25"
Depth  = 3.625"

![Way Huge Pork   Pickle Small](https://user-images.githubusercontent.com/103243414/162384349-ddcccd67-2150-46b0-9a5b-45c556457ac1.jpg)

**Comment by ArislanShiva** [comment]
It's already in the database

**Comment by grgbikas** [comment]
it's the smaller Version. The one in the data base is older(Large) one. Please add this one i humbly request. Thank you.
