### ISSUE TITLE
Electro-Harmonix Pedals to Add

### ISSUE THREAD

**Issue by ZiPan77** [PedalPlayground/PedalPlayground.github.io#90]
[Electro-Harmonix Deluxe Electric Mistress](https://cdn.shopify.com/s/files/1/0788/1755/products/c03ce29a-f8cb-430e-b693-83f78cdecdb1_a17b8a94-ce96-4f21-acdb-deb3a33ad185.jpg?v=1544425173) measures 4.75" x 4"
[Electro-Harmonix Stereo Electric Mistress](https://media.sweetwater.com/api/i/f-webp__q-82__ha-e1eec93d83939e1b__hmac-383f1e032e9d7790edfd9782c751c711f7f96777/images/items/750/ElMistressSt-large.jpg.auto.webp) measures 6.2" x 5.6"

**Comment by tehtrav** [comment]
Closing this as these are both available, thanks!
