### ISSUE TITLE
ThorpyFX The Fallout Cloud Fuzz

### ISSUE THREAD

**Issue by XlosVSM** [PedalPlayground/PedalPlayground.github.io#914]

**Comment by jfmguitarist** [comment]
Already added.... listed as ThorpyFX Fallout Cloud

![Screen Shot 2022-04-17 at 11 02 31 PM](https://user-images.githubusercontent.com/101024313/163748023-c03832bf-5483-4eb0-aba5-48018eacadf8.png)
