### ISSUE TITLE
Question about photo format

### ISSUE THREAD

**Issue by tandrewnichols** [PedalPlayground/PedalPlayground.github.io#94]
When you say to save as PNG-24, do you actually mean PNG-32? Because PNG-24 has no alpha channel and therefore no transparent background. For context, I'm not big in graphic-related things, so maybe I just don't really understand. I also don't have Photoshop so I'm working in Gimp. Maybe Photoshop does some magic behind the scenes, but I'm assuming you do want the transparency preserved, right?

**Comment by tehtrav** [comment]
I believe PNG24 should preserve transparency but I’m guessing 32 will work fine as well!

**Comment by tandrewnichols** [comment]
If I figure this out, I'll add instructions for Gimp to the readme cause it's not exactly straight-forward.
