### ISSUE TITLE
Pedal Request: Lehle Mono Volume S (small version)

### ISSUE THREAD

**Issue by Benjamin-RM** [PedalPlayground/PedalPlayground.github.io#947]
IMAGE to source

Looks identical to the expression pedal they make? Not sure if it's the same housing or not

**Dimensions**

H: 4,7 cm
W: 9 cm
D: 20 cm

https://effektpedaler.dk/en/product/lehle-mono-volume-s/

**Comment by Ripley63** [comment]
![LehleMonoVolS](https://user-images.githubusercontent.com/85568509/172730273-17a10f63-47ab-4c21-8ab5-c00029bc41e7.png)

**Comment by Ripley63** [comment]
Image added

**Comment by Benjamin-RM** [comment]
According to Lehle, this small volume pedal has the same housing and, I believe, appearance as the Dual Expression. Perhaps adding it is not really needed?

**Comment by Ripley63** [comment]
I don't know, I just saw that the OP didn't include an image, that's it.
I just wanted to contribute.
