### ISSUE TITLE
Pedal Sizing Incorrect: Sola Sound Pedals

### ISSUE THREAD

**Issue by Benjamin-RM** [PedalPlayground/PedalPlayground.github.io#962]
Both the **Sola Sound MK1 Tonebender** and **Sola Sound SCB Tonebender** are _massively oversized_. See the **Sola Sound The Yellow Hybrid** in the same category to see by how much 😂

**Comment by ArislanShiva** [comment]
I  wasn't sure of the exact measurements of either pedal.  I just used a height of 8.5 inches as an approximate.

**Comment by ArislanShiva** [comment]
The guy who originally added the pedal to the database must have used the dimensions of the packaging or something.  😂
